-- Emergency rollback for the FINAL tenant-relationship state, including
-- preserve_postgrest_relationship_names. Restores original single-column FKs.
-- Reopens cross-tenant attachment risk. Review before executing; never automated.
begin;
set local lock_timeout='3s';
alter table public.audit_actions drop constraint audit_actions_evidence_id_fkey, add constraint audit_actions_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES evidence(id) ON DELETE SET NULL;
alter table public.audit_actions drop constraint audit_actions_observation_id_fkey, add constraint audit_actions_observation_id_fkey FOREIGN KEY (observation_id) REFERENCES audit_observations(id) ON DELETE CASCADE;
alter table public.audit_actions drop constraint audit_actions_owner_id_fkey, add constraint audit_actions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_actions drop constraint audit_actions_verified_by_fkey, add constraint audit_actions_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_engagements drop constraint audit_engagements_auditee_owner_id_fkey, add constraint audit_engagements_auditee_owner_id_fkey FOREIGN KEY (auditee_owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_engagements drop constraint audit_engagements_lead_auditor_id_fkey, add constraint audit_engagements_lead_auditor_id_fkey FOREIGN KEY (lead_auditor_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_engagements drop constraint audit_engagements_plan_item_id_fkey, add constraint audit_engagements_plan_item_id_fkey FOREIGN KEY (plan_item_id) REFERENCES audit_plan_items(id) ON DELETE SET NULL;
alter table public.audit_engagements drop constraint audit_engagements_universe_id_fkey, add constraint audit_engagements_universe_id_fkey FOREIGN KEY (universe_id) REFERENCES audit_universe(id) ON DELETE SET NULL;
alter table public.audit_observations drop constraint audit_observations_engagement_id_fkey, add constraint audit_observations_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES audit_engagements(id) ON DELETE CASCADE;
alter table public.audit_observations drop constraint audit_observations_icfr_control_id_fkey, add constraint audit_observations_icfr_control_id_fkey FOREIGN KEY (icfr_control_id) REFERENCES icfr_controls(id) ON DELETE SET NULL;
alter table public.audit_plan_items drop constraint audit_plan_items_engagement_id_fkey, add constraint audit_plan_items_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES audit_engagements(id) ON DELETE SET NULL;
alter table public.audit_plan_items drop constraint audit_plan_items_plan_id_fkey, add constraint audit_plan_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES audit_plans(id) ON DELETE CASCADE;
alter table public.audit_plan_items drop constraint audit_plan_items_universe_id_fkey, add constraint audit_plan_items_universe_id_fkey FOREIGN KEY (universe_id) REFERENCES audit_universe(id) ON DELETE SET NULL;
alter table public.audit_plans drop constraint audit_plans_approved_by_fkey, add constraint audit_plans_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_procedures drop constraint audit_procedures_assigned_to_fkey, add constraint audit_procedures_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_procedures drop constraint audit_procedures_engagement_id_fkey, add constraint audit_procedures_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES audit_engagements(id) ON DELETE CASCADE;
alter table public.audit_universe drop constraint audit_universe_owner_id_fkey, add constraint audit_universe_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_universe drop constraint audit_universe_parent_id_fkey, add constraint audit_universe_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES audit_universe(id) ON DELETE SET NULL;
alter table public.audit_workpapers drop constraint audit_workpapers_engagement_id_fkey, add constraint audit_workpapers_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES audit_engagements(id) ON DELETE CASCADE;
alter table public.audit_workpapers drop constraint audit_workpapers_evidence_id_fkey, add constraint audit_workpapers_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES evidence(id) ON DELETE SET NULL;
alter table public.audit_workpapers drop constraint audit_workpapers_prepared_by_fkey, add constraint audit_workpapers_prepared_by_fkey FOREIGN KEY (prepared_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.audit_workpapers drop constraint audit_workpapers_procedure_id_fkey, add constraint audit_workpapers_procedure_id_fkey FOREIGN KEY (procedure_id) REFERENCES audit_procedures(id) ON DELETE SET NULL;
alter table public.audit_workpapers drop constraint audit_workpapers_reviewed_by_fkey, add constraint audit_workpapers_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.briefs drop constraint briefs_client_workspace_id_fkey, add constraint briefs_client_workspace_id_fkey FOREIGN KEY (client_workspace_id) REFERENCES client_workspaces(id) ON DELETE CASCADE;
alter table public.conversations drop constraint conversations_created_by_fkey, add constraint conversations_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_appetite drop constraint erm_appetite_approved_by_fkey, add constraint erm_appetite_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_appetite drop constraint erm_appetite_category_id_fkey, add constraint erm_appetite_category_id_fkey FOREIGN KEY (category_id) REFERENCES erm_categories(id) ON DELETE CASCADE;
alter table public.erm_assessments drop constraint erm_assessments_assessed_by_fkey, add constraint erm_assessments_assessed_by_fkey FOREIGN KEY (assessed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_assessments drop constraint erm_assessments_risk_id_fkey, add constraint erm_assessments_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES erm_risks(id) ON DELETE CASCADE;
alter table public.erm_categories drop constraint erm_categories_parent_id_fkey, add constraint erm_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES erm_categories(id) ON DELETE CASCADE;
alter table public.erm_kri_readings drop constraint erm_kri_readings_kri_id_fkey, add constraint erm_kri_readings_kri_id_fkey FOREIGN KEY (kri_id) REFERENCES erm_kris(id) ON DELETE CASCADE;
alter table public.erm_kri_readings drop constraint erm_kri_readings_recorded_by_fkey, add constraint erm_kri_readings_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_kris drop constraint erm_kris_owner_id_fkey, add constraint erm_kris_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_kris drop constraint erm_kris_risk_id_fkey, add constraint erm_kris_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES erm_risks(id) ON DELETE CASCADE;
alter table public.erm_links drop constraint erm_links_risk_id_fkey, add constraint erm_links_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES erm_risks(id) ON DELETE CASCADE;
alter table public.erm_risk_controls drop constraint erm_risk_controls_icfr_control_id_fkey, add constraint erm_risk_controls_icfr_control_id_fkey FOREIGN KEY (icfr_control_id) REFERENCES icfr_controls(id) ON DELETE CASCADE;
alter table public.erm_risk_controls drop constraint erm_risk_controls_risk_id_fkey, add constraint erm_risk_controls_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES erm_risks(id) ON DELETE CASCADE;
alter table public.erm_risks drop constraint erm_risks_category_id_fkey, add constraint erm_risks_category_id_fkey FOREIGN KEY (category_id) REFERENCES erm_categories(id) ON DELETE SET NULL;
alter table public.erm_risks drop constraint erm_risks_client_workspace_id_fkey, add constraint erm_risks_client_workspace_id_fkey FOREIGN KEY (client_workspace_id) REFERENCES client_workspaces(id) ON DELETE SET NULL;
alter table public.erm_risks drop constraint erm_risks_created_by_fkey, add constraint erm_risks_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_risks drop constraint erm_risks_owner_id_fkey, add constraint erm_risks_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_risks drop constraint erm_risks_sponsor_id_fkey, add constraint erm_risks_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_treatments drop constraint erm_treatments_owner_id_fkey, add constraint erm_treatments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.erm_treatments drop constraint erm_treatments_risk_id_fkey, add constraint erm_treatments_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES erm_risks(id) ON DELETE CASCADE;
alter table public.evidence drop constraint evidence_reviewed_by_fkey, add constraint evidence_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.evidence drop constraint evidence_uploaded_by_fkey, add constraint evidence_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.icfr_controls drop constraint icfr_controls_owner_id_fkey, add constraint icfr_controls_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.icfr_controls drop constraint icfr_controls_process_id_fkey, add constraint icfr_controls_process_id_fkey FOREIGN KEY (process_id) REFERENCES icfr_processes(id) ON DELETE CASCADE;
alter table public.icfr_deficiencies drop constraint icfr_deficiencies_control_id_fkey, add constraint icfr_deficiencies_control_id_fkey FOREIGN KEY (control_id) REFERENCES icfr_controls(id) ON DELETE CASCADE;
alter table public.icfr_deficiencies drop constraint icfr_deficiencies_owner_id_fkey, add constraint icfr_deficiencies_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.icfr_deficiencies drop constraint icfr_deficiencies_test_id_fkey, add constraint icfr_deficiencies_test_id_fkey FOREIGN KEY (test_id) REFERENCES icfr_tests(id) ON DELETE SET NULL;
alter table public.icfr_processes drop constraint icfr_processes_client_workspace_id_fkey, add constraint icfr_processes_client_workspace_id_fkey FOREIGN KEY (client_workspace_id) REFERENCES client_workspaces(id) ON DELETE SET NULL;
alter table public.icfr_processes drop constraint icfr_processes_owner_id_fkey, add constraint icfr_processes_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.icfr_risks drop constraint icfr_risks_process_id_fkey, add constraint icfr_risks_process_id_fkey FOREIGN KEY (process_id) REFERENCES icfr_processes(id) ON DELETE CASCADE;
alter table public.icfr_tests drop constraint icfr_tests_control_id_fkey, add constraint icfr_tests_control_id_fkey FOREIGN KEY (control_id) REFERENCES icfr_controls(id) ON DELETE CASCADE;
alter table public.icfr_tests drop constraint icfr_tests_tester_id_fkey, add constraint icfr_tests_tester_id_fkey FOREIGN KEY (tester_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.policies drop constraint policies_client_workspace_id_fkey, add constraint policies_client_workspace_id_fkey FOREIGN KEY (client_workspace_id) REFERENCES client_workspaces(id) ON DELETE SET NULL;
alter table public.policies drop constraint policies_created_by_fkey, add constraint policies_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.programs drop constraint programs_client_workspace_id_fkey, add constraint programs_client_workspace_id_fkey FOREIGN KEY (client_workspace_id) REFERENCES client_workspaces(id) ON DELETE SET NULL;
alter table public.programs drop constraint programs_created_by_fkey, add constraint programs_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
drop index public.audit_actions_evidence_id_tenant_idx;
drop index public.audit_actions_observation_id_tenant_idx;
drop index public.audit_actions_owner_id_tenant_idx;
drop index public.audit_actions_verified_by_tenant_idx;
drop index public.audit_engagements_auditee_owner_id_tenant_idx;
drop index public.audit_engagements_lead_auditor_id_tenant_idx;
drop index public.audit_engagements_plan_item_id_tenant_idx;
drop index public.audit_engagements_universe_id_tenant_idx;
drop index public.audit_observations_engagement_id_tenant_idx;
drop index public.audit_observations_icfr_control_id_tenant_idx;
drop index public.audit_plan_items_engagement_id_tenant_idx;
drop index public.audit_plan_items_plan_id_tenant_idx;
drop index public.audit_plan_items_universe_id_tenant_idx;
drop index public.audit_plans_approved_by_tenant_idx;
drop index public.audit_procedures_assigned_to_tenant_idx;
drop index public.audit_procedures_engagement_id_tenant_idx;
drop index public.audit_universe_owner_id_tenant_idx;
drop index public.audit_universe_parent_id_tenant_idx;
drop index public.audit_workpapers_engagement_id_tenant_idx;
drop index public.audit_workpapers_evidence_id_tenant_idx;
drop index public.audit_workpapers_prepared_by_tenant_idx;
drop index public.audit_workpapers_procedure_id_tenant_idx;
drop index public.audit_workpapers_reviewed_by_tenant_idx;
drop index public.briefs_client_workspace_id_tenant_idx;
drop index public.conversations_created_by_tenant_idx;
drop index public.erm_appetite_approved_by_tenant_idx;
drop index public.erm_appetite_category_id_tenant_idx;
drop index public.erm_assessments_assessed_by_tenant_idx;
drop index public.erm_assessments_risk_id_tenant_idx;
drop index public.erm_categories_parent_id_tenant_idx;
drop index public.erm_kri_readings_kri_id_tenant_idx;
drop index public.erm_kri_readings_recorded_by_tenant_idx;
drop index public.erm_kris_owner_id_tenant_idx;
drop index public.erm_kris_risk_id_tenant_idx;
drop index public.erm_links_risk_id_tenant_idx;
drop index public.erm_risk_controls_icfr_control_id_tenant_idx;
drop index public.erm_risk_controls_risk_id_tenant_idx;
drop index public.erm_risks_category_id_tenant_idx;
drop index public.erm_risks_client_workspace_id_tenant_idx;
drop index public.erm_risks_created_by_tenant_idx;
drop index public.erm_risks_owner_id_tenant_idx;
drop index public.erm_risks_sponsor_id_tenant_idx;
drop index public.erm_treatments_owner_id_tenant_idx;
drop index public.erm_treatments_risk_id_tenant_idx;
drop index public.evidence_reviewed_by_tenant_idx;
drop index public.evidence_uploaded_by_tenant_idx;
drop index public.icfr_controls_owner_id_tenant_idx;
drop index public.icfr_controls_process_id_tenant_idx;
drop index public.icfr_deficiencies_control_id_tenant_idx;
drop index public.icfr_deficiencies_owner_id_tenant_idx;
drop index public.icfr_deficiencies_test_id_tenant_idx;
drop index public.icfr_processes_client_workspace_id_tenant_idx;
drop index public.icfr_processes_owner_id_tenant_idx;
drop index public.icfr_risks_process_id_tenant_idx;
drop index public.icfr_tests_control_id_tenant_idx;
drop index public.icfr_tests_tester_id_tenant_idx;
drop index public.policies_client_workspace_id_tenant_idx;
drop index public.policies_created_by_tenant_idx;
drop index public.programs_client_workspace_id_tenant_idx;
drop index public.programs_created_by_tenant_idx;
drop index public.audit_engagements_tenant_identity_uidx;
drop index public.audit_observations_tenant_identity_uidx;
drop index public.audit_plan_items_tenant_identity_uidx;
drop index public.audit_plans_tenant_identity_uidx;
drop index public.audit_procedures_tenant_identity_uidx;
drop index public.audit_universe_tenant_identity_uidx;
drop index public.client_workspaces_tenant_identity_uidx;
drop index public.erm_categories_tenant_identity_uidx;
drop index public.erm_kris_tenant_identity_uidx;
drop index public.erm_risks_tenant_identity_uidx;
drop index public.evidence_tenant_identity_uidx;
drop index public.icfr_controls_tenant_identity_uidx;
drop index public.icfr_processes_tenant_identity_uidx;
drop index public.icfr_tests_tenant_identity_uidx;
drop index public.profiles_tenant_identity_uidx;
notify pgrst, 'reload schema';
commit;
