-- Retain one FK per relationship and the original constraint names used by
-- PostgREST embed hints. Replace duplicate old/new FKs atomically, preserving
-- CASCADE and column-specific SET NULL (organization_id must remain intact).
set local lock_timeout='3s';
set local statement_timeout='60s';
alter table public.audit_actions drop constraint audit_actions_evidence_id_fkey, drop constraint audit_actions_evidence_id_tenant_fk, add constraint audit_actions_evidence_id_fkey foreign key (evidence_id, organization_id) references public.evidence (id, organization_id) on delete set null (evidence_id) not valid;
alter table public.audit_actions drop constraint audit_actions_observation_id_fkey, drop constraint audit_actions_observation_id_tenant_fk, add constraint audit_actions_observation_id_fkey foreign key (observation_id, organization_id) references public.audit_observations (id, organization_id) on delete cascade not valid;
alter table public.audit_actions drop constraint audit_actions_owner_id_fkey, drop constraint audit_actions_owner_id_tenant_fk, add constraint audit_actions_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.audit_actions drop constraint audit_actions_verified_by_fkey, drop constraint audit_actions_verified_by_tenant_fk, add constraint audit_actions_verified_by_fkey foreign key (verified_by, organization_id) references public.profiles (id, organization_id) on delete set null (verified_by) not valid;
alter table public.audit_engagements drop constraint audit_engagements_auditee_owner_id_fkey, drop constraint audit_engagements_auditee_owner_id_tenant_fk, add constraint audit_engagements_auditee_owner_id_fkey foreign key (auditee_owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (auditee_owner_id) not valid;
alter table public.audit_engagements drop constraint audit_engagements_lead_auditor_id_fkey, drop constraint audit_engagements_lead_auditor_id_tenant_fk, add constraint audit_engagements_lead_auditor_id_fkey foreign key (lead_auditor_id, organization_id) references public.profiles (id, organization_id) on delete set null (lead_auditor_id) not valid;
alter table public.audit_engagements drop constraint audit_engagements_plan_item_id_fkey, drop constraint audit_engagements_plan_item_id_tenant_fk, add constraint audit_engagements_plan_item_id_fkey foreign key (plan_item_id, organization_id) references public.audit_plan_items (id, organization_id) on delete set null (plan_item_id) not valid;
alter table public.audit_engagements drop constraint audit_engagements_universe_id_fkey, drop constraint audit_engagements_universe_id_tenant_fk, add constraint audit_engagements_universe_id_fkey foreign key (universe_id, organization_id) references public.audit_universe (id, organization_id) on delete set null (universe_id) not valid;
alter table public.audit_observations drop constraint audit_observations_engagement_id_fkey, drop constraint audit_observations_engagement_id_tenant_fk, add constraint audit_observations_engagement_id_fkey foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) on delete cascade not valid;
alter table public.audit_observations drop constraint audit_observations_icfr_control_id_fkey, drop constraint audit_observations_icfr_control_id_tenant_fk, add constraint audit_observations_icfr_control_id_fkey foreign key (icfr_control_id, organization_id) references public.icfr_controls (id, organization_id) on delete set null (icfr_control_id) not valid;
alter table public.audit_plan_items drop constraint audit_plan_items_engagement_id_fkey, drop constraint audit_plan_items_engagement_id_tenant_fk, add constraint audit_plan_items_engagement_id_fkey foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) on delete set null (engagement_id) not valid;
alter table public.audit_plan_items drop constraint audit_plan_items_plan_id_fkey, drop constraint audit_plan_items_plan_id_tenant_fk, add constraint audit_plan_items_plan_id_fkey foreign key (plan_id, organization_id) references public.audit_plans (id, organization_id) on delete cascade not valid;
alter table public.audit_plan_items drop constraint audit_plan_items_universe_id_fkey, drop constraint audit_plan_items_universe_id_tenant_fk, add constraint audit_plan_items_universe_id_fkey foreign key (universe_id, organization_id) references public.audit_universe (id, organization_id) on delete set null (universe_id) not valid;
alter table public.audit_plans drop constraint audit_plans_approved_by_fkey, drop constraint audit_plans_approved_by_tenant_fk, add constraint audit_plans_approved_by_fkey foreign key (approved_by, organization_id) references public.profiles (id, organization_id) on delete set null (approved_by) not valid;
alter table public.audit_procedures drop constraint audit_procedures_assigned_to_fkey, drop constraint audit_procedures_assigned_to_tenant_fk, add constraint audit_procedures_assigned_to_fkey foreign key (assigned_to, organization_id) references public.profiles (id, organization_id) on delete set null (assigned_to) not valid;
alter table public.audit_procedures drop constraint audit_procedures_engagement_id_fkey, drop constraint audit_procedures_engagement_id_tenant_fk, add constraint audit_procedures_engagement_id_fkey foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) on delete cascade not valid;
alter table public.audit_universe drop constraint audit_universe_owner_id_fkey, drop constraint audit_universe_owner_id_tenant_fk, add constraint audit_universe_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.audit_universe drop constraint audit_universe_parent_id_fkey, drop constraint audit_universe_parent_id_tenant_fk, add constraint audit_universe_parent_id_fkey foreign key (parent_id, organization_id) references public.audit_universe (id, organization_id) on delete set null (parent_id) not valid;
alter table public.audit_workpapers drop constraint audit_workpapers_engagement_id_fkey, drop constraint audit_workpapers_engagement_id_tenant_fk, add constraint audit_workpapers_engagement_id_fkey foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) on delete cascade not valid;
alter table public.audit_workpapers drop constraint audit_workpapers_evidence_id_fkey, drop constraint audit_workpapers_evidence_id_tenant_fk, add constraint audit_workpapers_evidence_id_fkey foreign key (evidence_id, organization_id) references public.evidence (id, organization_id) on delete set null (evidence_id) not valid;
alter table public.audit_workpapers drop constraint audit_workpapers_prepared_by_fkey, drop constraint audit_workpapers_prepared_by_tenant_fk, add constraint audit_workpapers_prepared_by_fkey foreign key (prepared_by, organization_id) references public.profiles (id, organization_id) on delete set null (prepared_by) not valid;
alter table public.audit_workpapers drop constraint audit_workpapers_procedure_id_fkey, drop constraint audit_workpapers_procedure_id_tenant_fk, add constraint audit_workpapers_procedure_id_fkey foreign key (procedure_id, organization_id) references public.audit_procedures (id, organization_id) on delete set null (procedure_id) not valid;
alter table public.audit_workpapers drop constraint audit_workpapers_reviewed_by_fkey, drop constraint audit_workpapers_reviewed_by_tenant_fk, add constraint audit_workpapers_reviewed_by_fkey foreign key (reviewed_by, organization_id) references public.profiles (id, organization_id) on delete set null (reviewed_by) not valid;
alter table public.briefs drop constraint briefs_client_workspace_id_fkey, drop constraint briefs_client_workspace_id_tenant_fk, add constraint briefs_client_workspace_id_fkey foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) on delete cascade not valid;
alter table public.conversations drop constraint conversations_created_by_fkey, drop constraint conversations_created_by_tenant_fk, add constraint conversations_created_by_fkey foreign key (created_by, organization_id) references public.profiles (id, organization_id) on delete set null (created_by) not valid;
alter table public.erm_appetite drop constraint erm_appetite_approved_by_fkey, drop constraint erm_appetite_approved_by_tenant_fk, add constraint erm_appetite_approved_by_fkey foreign key (approved_by, organization_id) references public.profiles (id, organization_id) on delete set null (approved_by) not valid;
alter table public.erm_appetite drop constraint erm_appetite_category_id_fkey, drop constraint erm_appetite_category_id_tenant_fk, add constraint erm_appetite_category_id_fkey foreign key (category_id, organization_id) references public.erm_categories (id, organization_id) on delete cascade not valid;
alter table public.erm_assessments drop constraint erm_assessments_assessed_by_fkey, drop constraint erm_assessments_assessed_by_tenant_fk, add constraint erm_assessments_assessed_by_fkey foreign key (assessed_by, organization_id) references public.profiles (id, organization_id) on delete set null (assessed_by) not valid;
alter table public.erm_assessments drop constraint erm_assessments_risk_id_fkey, drop constraint erm_assessments_risk_id_tenant_fk, add constraint erm_assessments_risk_id_fkey foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) on delete cascade not valid;
alter table public.erm_categories drop constraint erm_categories_parent_id_fkey, drop constraint erm_categories_parent_id_tenant_fk, add constraint erm_categories_parent_id_fkey foreign key (parent_id, organization_id) references public.erm_categories (id, organization_id) on delete cascade not valid;
alter table public.erm_kri_readings drop constraint erm_kri_readings_kri_id_fkey, drop constraint erm_kri_readings_kri_id_tenant_fk, add constraint erm_kri_readings_kri_id_fkey foreign key (kri_id, organization_id) references public.erm_kris (id, organization_id) on delete cascade not valid;
alter table public.erm_kri_readings drop constraint erm_kri_readings_recorded_by_fkey, drop constraint erm_kri_readings_recorded_by_tenant_fk, add constraint erm_kri_readings_recorded_by_fkey foreign key (recorded_by, organization_id) references public.profiles (id, organization_id) on delete set null (recorded_by) not valid;
alter table public.erm_kris drop constraint erm_kris_owner_id_fkey, drop constraint erm_kris_owner_id_tenant_fk, add constraint erm_kris_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.erm_kris drop constraint erm_kris_risk_id_fkey, drop constraint erm_kris_risk_id_tenant_fk, add constraint erm_kris_risk_id_fkey foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) on delete cascade not valid;
alter table public.erm_links drop constraint erm_links_risk_id_fkey, drop constraint erm_links_risk_id_tenant_fk, add constraint erm_links_risk_id_fkey foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) on delete cascade not valid;
alter table public.erm_risk_controls drop constraint erm_risk_controls_icfr_control_id_fkey, drop constraint erm_risk_controls_icfr_control_id_tenant_fk, add constraint erm_risk_controls_icfr_control_id_fkey foreign key (icfr_control_id, organization_id) references public.icfr_controls (id, organization_id) on delete cascade not valid;
alter table public.erm_risk_controls drop constraint erm_risk_controls_risk_id_fkey, drop constraint erm_risk_controls_risk_id_tenant_fk, add constraint erm_risk_controls_risk_id_fkey foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) on delete cascade not valid;
alter table public.erm_risks drop constraint erm_risks_category_id_fkey, drop constraint erm_risks_category_id_tenant_fk, add constraint erm_risks_category_id_fkey foreign key (category_id, organization_id) references public.erm_categories (id, organization_id) on delete set null (category_id) not valid;
alter table public.erm_risks drop constraint erm_risks_client_workspace_id_fkey, drop constraint erm_risks_client_workspace_id_tenant_fk, add constraint erm_risks_client_workspace_id_fkey foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) on delete set null (client_workspace_id) not valid;
alter table public.erm_risks drop constraint erm_risks_created_by_fkey, drop constraint erm_risks_created_by_tenant_fk, add constraint erm_risks_created_by_fkey foreign key (created_by, organization_id) references public.profiles (id, organization_id) on delete set null (created_by) not valid;
alter table public.erm_risks drop constraint erm_risks_owner_id_fkey, drop constraint erm_risks_owner_id_tenant_fk, add constraint erm_risks_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.erm_risks drop constraint erm_risks_sponsor_id_fkey, drop constraint erm_risks_sponsor_id_tenant_fk, add constraint erm_risks_sponsor_id_fkey foreign key (sponsor_id, organization_id) references public.profiles (id, organization_id) on delete set null (sponsor_id) not valid;
alter table public.erm_treatments drop constraint erm_treatments_owner_id_fkey, drop constraint erm_treatments_owner_id_tenant_fk, add constraint erm_treatments_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.erm_treatments drop constraint erm_treatments_risk_id_fkey, drop constraint erm_treatments_risk_id_tenant_fk, add constraint erm_treatments_risk_id_fkey foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) on delete cascade not valid;
alter table public.evidence drop constraint evidence_reviewed_by_fkey, drop constraint evidence_reviewed_by_tenant_fk, add constraint evidence_reviewed_by_fkey foreign key (reviewed_by, organization_id) references public.profiles (id, organization_id) on delete set null (reviewed_by) not valid;
alter table public.evidence drop constraint evidence_uploaded_by_fkey, drop constraint evidence_uploaded_by_tenant_fk, add constraint evidence_uploaded_by_fkey foreign key (uploaded_by, organization_id) references public.profiles (id, organization_id) on delete set null (uploaded_by) not valid;
alter table public.icfr_controls drop constraint icfr_controls_owner_id_fkey, drop constraint icfr_controls_owner_id_tenant_fk, add constraint icfr_controls_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.icfr_controls drop constraint icfr_controls_process_id_fkey, drop constraint icfr_controls_process_id_tenant_fk, add constraint icfr_controls_process_id_fkey foreign key (process_id, organization_id) references public.icfr_processes (id, organization_id) on delete cascade not valid;
alter table public.icfr_deficiencies drop constraint icfr_deficiencies_control_id_fkey, drop constraint icfr_deficiencies_control_id_tenant_fk, add constraint icfr_deficiencies_control_id_fkey foreign key (control_id, organization_id) references public.icfr_controls (id, organization_id) on delete cascade not valid;
alter table public.icfr_deficiencies drop constraint icfr_deficiencies_owner_id_fkey, drop constraint icfr_deficiencies_owner_id_tenant_fk, add constraint icfr_deficiencies_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.icfr_deficiencies drop constraint icfr_deficiencies_test_id_fkey, drop constraint icfr_deficiencies_test_id_tenant_fk, add constraint icfr_deficiencies_test_id_fkey foreign key (test_id, organization_id) references public.icfr_tests (id, organization_id) on delete set null (test_id) not valid;
alter table public.icfr_processes drop constraint icfr_processes_client_workspace_id_fkey, drop constraint icfr_processes_client_workspace_id_tenant_fk, add constraint icfr_processes_client_workspace_id_fkey foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) on delete set null (client_workspace_id) not valid;
alter table public.icfr_processes drop constraint icfr_processes_owner_id_fkey, drop constraint icfr_processes_owner_id_tenant_fk, add constraint icfr_processes_owner_id_fkey foreign key (owner_id, organization_id) references public.profiles (id, organization_id) on delete set null (owner_id) not valid;
alter table public.icfr_risks drop constraint icfr_risks_process_id_fkey, drop constraint icfr_risks_process_id_tenant_fk, add constraint icfr_risks_process_id_fkey foreign key (process_id, organization_id) references public.icfr_processes (id, organization_id) on delete cascade not valid;
alter table public.icfr_tests drop constraint icfr_tests_control_id_fkey, drop constraint icfr_tests_control_id_tenant_fk, add constraint icfr_tests_control_id_fkey foreign key (control_id, organization_id) references public.icfr_controls (id, organization_id) on delete cascade not valid;
alter table public.icfr_tests drop constraint icfr_tests_tester_id_fkey, drop constraint icfr_tests_tester_id_tenant_fk, add constraint icfr_tests_tester_id_fkey foreign key (tester_id, organization_id) references public.profiles (id, organization_id) on delete set null (tester_id) not valid;
alter table public.policies drop constraint policies_client_workspace_id_fkey, drop constraint policies_client_workspace_id_tenant_fk, add constraint policies_client_workspace_id_fkey foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) on delete set null (client_workspace_id) not valid;
alter table public.policies drop constraint policies_created_by_fkey, drop constraint policies_created_by_tenant_fk, add constraint policies_created_by_fkey foreign key (created_by, organization_id) references public.profiles (id, organization_id) on delete set null (created_by) not valid;
alter table public.programs drop constraint programs_client_workspace_id_fkey, drop constraint programs_client_workspace_id_tenant_fk, add constraint programs_client_workspace_id_fkey foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) on delete set null (client_workspace_id) not valid;
alter table public.programs drop constraint programs_created_by_fkey, drop constraint programs_created_by_tenant_fk, add constraint programs_created_by_fkey foreign key (created_by, organization_id) references public.profiles (id, organization_id) on delete set null (created_by) not valid;
alter table public.audit_actions validate constraint audit_actions_evidence_id_fkey;
alter table public.audit_actions validate constraint audit_actions_observation_id_fkey;
alter table public.audit_actions validate constraint audit_actions_owner_id_fkey;
alter table public.audit_actions validate constraint audit_actions_verified_by_fkey;
alter table public.audit_engagements validate constraint audit_engagements_auditee_owner_id_fkey;
alter table public.audit_engagements validate constraint audit_engagements_lead_auditor_id_fkey;
alter table public.audit_engagements validate constraint audit_engagements_plan_item_id_fkey;
alter table public.audit_engagements validate constraint audit_engagements_universe_id_fkey;
alter table public.audit_observations validate constraint audit_observations_engagement_id_fkey;
alter table public.audit_observations validate constraint audit_observations_icfr_control_id_fkey;
alter table public.audit_plan_items validate constraint audit_plan_items_engagement_id_fkey;
alter table public.audit_plan_items validate constraint audit_plan_items_plan_id_fkey;
alter table public.audit_plan_items validate constraint audit_plan_items_universe_id_fkey;
alter table public.audit_plans validate constraint audit_plans_approved_by_fkey;
alter table public.audit_procedures validate constraint audit_procedures_assigned_to_fkey;
alter table public.audit_procedures validate constraint audit_procedures_engagement_id_fkey;
alter table public.audit_universe validate constraint audit_universe_owner_id_fkey;
alter table public.audit_universe validate constraint audit_universe_parent_id_fkey;
alter table public.audit_workpapers validate constraint audit_workpapers_engagement_id_fkey;
alter table public.audit_workpapers validate constraint audit_workpapers_evidence_id_fkey;
alter table public.audit_workpapers validate constraint audit_workpapers_prepared_by_fkey;
alter table public.audit_workpapers validate constraint audit_workpapers_procedure_id_fkey;
alter table public.audit_workpapers validate constraint audit_workpapers_reviewed_by_fkey;
alter table public.briefs validate constraint briefs_client_workspace_id_fkey;
alter table public.conversations validate constraint conversations_created_by_fkey;
alter table public.erm_appetite validate constraint erm_appetite_approved_by_fkey;
alter table public.erm_appetite validate constraint erm_appetite_category_id_fkey;
alter table public.erm_assessments validate constraint erm_assessments_assessed_by_fkey;
alter table public.erm_assessments validate constraint erm_assessments_risk_id_fkey;
alter table public.erm_categories validate constraint erm_categories_parent_id_fkey;
alter table public.erm_kri_readings validate constraint erm_kri_readings_kri_id_fkey;
alter table public.erm_kri_readings validate constraint erm_kri_readings_recorded_by_fkey;
alter table public.erm_kris validate constraint erm_kris_owner_id_fkey;
alter table public.erm_kris validate constraint erm_kris_risk_id_fkey;
alter table public.erm_links validate constraint erm_links_risk_id_fkey;
alter table public.erm_risk_controls validate constraint erm_risk_controls_icfr_control_id_fkey;
alter table public.erm_risk_controls validate constraint erm_risk_controls_risk_id_fkey;
alter table public.erm_risks validate constraint erm_risks_category_id_fkey;
alter table public.erm_risks validate constraint erm_risks_client_workspace_id_fkey;
alter table public.erm_risks validate constraint erm_risks_created_by_fkey;
alter table public.erm_risks validate constraint erm_risks_owner_id_fkey;
alter table public.erm_risks validate constraint erm_risks_sponsor_id_fkey;
alter table public.erm_treatments validate constraint erm_treatments_owner_id_fkey;
alter table public.erm_treatments validate constraint erm_treatments_risk_id_fkey;
alter table public.evidence validate constraint evidence_reviewed_by_fkey;
alter table public.evidence validate constraint evidence_uploaded_by_fkey;
alter table public.icfr_controls validate constraint icfr_controls_owner_id_fkey;
alter table public.icfr_controls validate constraint icfr_controls_process_id_fkey;
alter table public.icfr_deficiencies validate constraint icfr_deficiencies_control_id_fkey;
alter table public.icfr_deficiencies validate constraint icfr_deficiencies_owner_id_fkey;
alter table public.icfr_deficiencies validate constraint icfr_deficiencies_test_id_fkey;
alter table public.icfr_processes validate constraint icfr_processes_client_workspace_id_fkey;
alter table public.icfr_processes validate constraint icfr_processes_owner_id_fkey;
alter table public.icfr_risks validate constraint icfr_risks_process_id_fkey;
alter table public.icfr_tests validate constraint icfr_tests_control_id_fkey;
alter table public.icfr_tests validate constraint icfr_tests_tester_id_fkey;
alter table public.policies validate constraint policies_client_workspace_id_fkey;
alter table public.policies validate constraint policies_created_by_fkey;
alter table public.programs validate constraint programs_client_workspace_id_fkey;
alter table public.programs validate constraint programs_created_by_fkey;
notify pgrst, 'reload schema';
