-- =============================================================================
-- AETHER ICFR — RCM template seed data
-- GENERATED FILE. Do not edit by hand.
-- Source: supabase/seed/icfr-templates/*.json
-- Rebuild: node scripts/build-icfr-templates.mjs
-- Generated: 2026-09-04T00:27:36.308Z
-- =============================================================================

begin;

-- ---------------------------------------------------------------------------
-- P2P: Procure-to-Pay (8 risks, 12 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('P2P', 'Procure-to-Pay', 'Procure-to-Pay', 'Purchasing, goods/services receipt, supplier invoice processing, accounts payable and disbursements. Covers vendor master data, purchase requisition and order approval, three-way match, payment release and AP reconciliation.', 10)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Purchases are made from unauthorized or fictitious vendors, or vendor master data (bank details) is changed without authorization, resulting in fraudulent or misdirected payments.', null, array['existence_occurrence', 'rights_obligations']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Purchase commitments are entered into without appropriate authorization or outside delegated authority limits.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Liabilities are recorded for goods or services not received, or at quantities/prices that do not agree to the purchase order and receipt.', null, array['existence_occurrence', 'accuracy', 'valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Goods and services received before period end are not accrued, or invoices are recorded in the wrong period (unrecorded liabilities).', null, array['completeness', 'cutoff']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Duplicate invoices are processed and paid, or payments are released for invoices that were not approved.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'Payments are released to the wrong payee, for the wrong amount, or without segregation between invoice approval and payment release.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'Accounts payable sub-ledger does not agree to the general ledger, and supplier balances are not reconciled to supplier statements.', null, array['completeness', 'accuracy', 'existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('risk', 'R8', 'Expenses are coded to the wrong account, cost centre or capital/expense classification.', null, array['accuracy', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 80),
  ('control', 'C1', 'Vendor master creation and change approval', 'New vendor set-up and changes to sensitive vendor master fields (name, bank account, tax registration, payment terms) are requested on a standard form with supporting documents (commercial registration, VAT certificate, bank letter), independently verified by Procurement via a call-back to a known contact, and approved by the AP Manager before the ERP change is released. The system generates a monthly vendor master change report that is reviewed by the Finance Manager for unauthorized changes.', null, 'preventive', 'it_dependent', 'event_driven', true, 'process', 'control_activities', array['R1', 'R6']::text[], 90),
  ('control', 'C2', 'Purchase requisition and PO approval workflow (DoA)', 'The ERP enforces a delegation-of-authority (DoA) workflow: purchase requisitions and purchase orders are routed to approvers based on value thresholds and cost centre, and cannot be released without the required approvals. The DoA matrix in the system is reconciled to the board-approved DoA policy annually.', null, 'preventive', 'automated', 'event_driven', true, 'process', 'control_activities', array['R2']::text[], 100),
  ('control', 'C3', 'Goods receipt recorded by independent receiving function', 'Goods receipt notes (GRN) are recorded in the ERP by warehouse/receiving staff who are independent of purchasing and AP, upon physical inspection of quantity and condition against the PO. Services receipt is confirmed by the requesting business owner in the system before invoice processing.', null, 'preventive', 'manual', 'multiple_daily', false, 'process', 'control_activities', array['R3']::text[], 110),
  ('control', 'C4', 'Automated three-way match', 'The ERP performs an automated three-way match of supplier invoice to PO and GRN on quantity and price within configured tolerances (e.g. 2% or SAR 500). Invoices outside tolerance are blocked for payment and routed to the buyer for resolution; blocked invoices over 30 days are reported to the AP Manager weekly.', null, 'preventive', 'automated', 'multiple_daily', true, 'process', 'control_activities', array['R3', 'R5']::text[], 120),
  ('control', 'C5', 'Non-PO invoice approval', 'Invoices without a purchase order (utilities, professional fees, rent) are approved by the budget holder per the DoA before posting, with the AP Supervisor verifying the approval evidence and account coding. Non-PO spend by category is reviewed monthly by the Finance Manager for reasonableness and policy compliance.', null, 'preventive', 'manual', 'daily', true, 'process', 'control_activities', array['R2', 'R3', 'R8']::text[], 130),
  ('control', 'C6', 'Duplicate invoice check', 'The ERP rejects invoice entry where the combination of vendor, invoice number and amount already exists. AP additionally runs a monthly fuzzy-match duplicate payment report (same vendor/amount within 30 days, similar invoice numbers) and investigates exceptions, recovering any duplicate payments.', null, 'preventive', 'automated', 'multiple_daily', true, 'process', 'control_activities', array['R5']::text[], 140),
  ('control', 'C7', 'Payment run review and release', 'The proposed payment run is generated from approved, due invoices only. The AP Supervisor reviews the payment proposal to supporting invoices for a sample and for all items above SAR 100,000, and the Treasury Manager (independent of AP) releases the bank file under dual authorization in the bank portal. Payment file totals are agreed to the ERP payment run.', null, 'preventive', 'it_dependent', 'weekly', true, 'process', 'control_activities', array['R5', 'R6']::text[], 150),
  ('control', 'C8', 'Unrecorded liabilities and GRNI accrual review', 'At month end, AP prepares an accrual for goods received not invoiced (GRNI report from ERP) and reviews post-period-end invoices and payments above SAR 20,000 to identify liabilities relating to the closed period. The Financial Controller reviews the accrual schedule, the ageing of GRNI items over 90 days, and the search for unrecorded liabilities, evidencing review by sign-off.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R4']::text[], 160),
  ('control', 'C9', 'AP sub-ledger to general ledger reconciliation', 'The AP sub-ledger is reconciled to the GL control account monthly; reconciling items are explained, aged and cleared within 60 days. The reconciliation is prepared by the AP Accountant and reviewed and signed by the Financial Controller within 5 working days of month end.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R7']::text[], 170),
  ('control', 'C10', 'Supplier statement reconciliation', 'Statements from the top 20 suppliers by spend and any supplier with disputed balances are reconciled to the AP sub-ledger quarterly. Differences are investigated and adjusted where valid; the reconciliation is reviewed by the AP Manager.', null, 'detective', 'manual', 'quarterly', false, 'process', 'control_activities', array['R4', 'R7']::text[], 180),
  ('control', 'C11', 'Segregation of duties in the P2P cycle', 'ERP role design prevents a single user from holding conflicting P2P access (vendor master maintenance, PO approval, GRN entry, invoice posting, payment release). Conflicts are analysed quarterly via an SoD ruleset report; any residual conflict is approved by the CFO with a documented mitigating control.', null, 'preventive', 'it_dependent', 'quarterly', true, 'process', 'control_activities', array['R1', 'R5', 'R6']::text[], 190),
  ('control', 'C12', 'Expense account coding review', 'AP staff code invoices to the GL account and cost centre indicated on the approved PO or requisition; the ERP restricts capital accounts to requisitions flagged as capex with an approved capital request number. The Management Accountant reviews the monthly expense variance by account and cost centre against budget and investigates variances above 10% and SAR 50,000.', null, 'detective', 'manual', 'monthly', false, 'process', 'control_activities', array['R8']::text[], 200)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'P2P'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'P2P'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12');

-- ---------------------------------------------------------------------------
-- O2C: Order-to-Cash (8 risks, 13 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('O2C', 'Order-to-Cash', 'Order-to-Cash', 'Customer master data, credit management, order acceptance, delivery, invoicing, revenue recognition, accounts receivable, cash application and expected credit loss provisioning under IFRS 15 and IFRS 9.', 20)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Sales are recorded for fictitious customers or for goods/services not delivered (or performance obligations not satisfied), overstating revenue.', null, array['existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Deliveries or services performed are not invoiced, or invoices are issued at incorrect prices, quantities or discounts.', null, array['completeness', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Revenue is recognized in the wrong period (early or late cut-off), including bill-and-hold, side agreements and pre-delivery invoicing around period end.', null, array['cutoff', 'existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Credit is extended to customers beyond approved limits or to customers with poor credit standing, resulting in uncollectible receivables.', null, array['valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Credit notes, returns and write-offs are processed without authorization, or are used to conceal cash misappropriation.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'Cash receipts are misapplied, applied to the wrong customer account, or not recorded (lapping/teeming and lading).', null, array['completeness', 'accuracy', 'existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'The expected credit loss (ECL) allowance is not calculated in accordance with IFRS 9 or is based on inaccurate ageing data, misstating net receivables.', null, array['valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('risk', 'R8', 'Contracts with multiple performance obligations, variable consideration or significant financing components are not identified and revenue is misallocated.', null, array['accuracy', 'valuation_allocation', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 80),
  ('control', 'C1', 'Customer master and credit limit approval', 'New customers are created only after a completed onboarding form with commercial registration and KYC documents, a credit assessment (financial statements, credit bureau/SIMAH report where available, trade references) and credit limit approval per the DoA. Changes to customer master fields, including credit limits and payment terms, follow the same approval and are reviewed on a monthly change report by the Credit Manager.', null, 'preventive', 'it_dependent', 'event_driven', true, 'process', 'control_activities', array['R1', 'R4']::text[], 90),
  ('control', 'C2', 'Automated credit check at order entry', 'The ERP performs an automated credit check on sales order creation and release; orders that would exceed the customer''s approved credit limit or where the account has overdue balances beyond 60 days are blocked. Blocked orders can be released only by the Credit Manager (or CFO above SAR 500,000) with documented rationale.', null, 'preventive', 'automated', 'multiple_daily', true, 'process', 'control_activities', array['R4']::text[], 100),
  ('control', 'C3', 'Contract review and revenue recognition assessment (IFRS 15)', 'Contracts above SAR 1 million or with non-standard terms (multiple deliverables, variable consideration, rebates, extended payment terms, acceptance clauses) are reviewed by Financial Reporting using the five-step model checklist before revenue recognition; the assessment identifies performance obligations, allocates the transaction price and documents the timing of recognition. The checklist is approved by the Financial Controller.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'control_activities', array['R8', 'R3']::text[], 110),
  ('control', 'C4', 'Invoicing triggered by proof of delivery / service acceptance', 'The ERP generates customer invoices automatically from delivery notes (goods) or from service confirmations approved by the customer or project manager (services), using prices and discounts from the approved price master and customer contract. Manual invoice creation and price overrides are restricted to the Billing Supervisor and reported monthly.', null, 'preventive', 'automated', 'multiple_daily', true, 'process', 'control_activities', array['R1', 'R2']::text[], 120),
  ('control', 'C5', 'Shipment-to-invoice completeness reconciliation', 'Billing reconciles delivery notes / service confirmations issued during the month to invoices raised, and investigates unbilled deliveries and any invoice without a matching delivery. The reconciliation is reviewed by the Revenue Accountant and open items older than 30 days are escalated to the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R2']::text[], 130),
  ('control', 'C6', 'Revenue cut-off review at period end', 'At each month end, Financial Reporting reviews deliveries and invoices five working days either side of the period end, sales orders shipped but not invoiced, invoices raised for undelivered goods, and any bill-and-hold arrangements, and posts cut-off adjustments as required. Deferred and accrued revenue schedules are reviewed and signed by the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R3']::text[], 140),
  ('control', 'C7', 'Credit note and write-off approval', 'Credit notes require a documented reason (return, pricing dispute, damaged goods) with supporting evidence, and are approved per the DoA (Sales Manager up to SAR 25,000; CFO above) by someone independent of the originating salesperson and of cash application. Bad debt write-offs require Credit Committee approval. A monthly credit note report by customer and reason is reviewed by the Financial Controller for unusual patterns.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'control_activities', array['R5']::text[], 150),
  ('control', 'C8', 'Daily cash application and unapplied cash review', 'Receipts from bank statements are applied to customer invoices daily by the Cash Application team using remittance advices; unapplied and unidentified receipts are followed up with customers and cleared within 15 days. The Credit Manager reviews the unapplied cash report weekly.', null, 'detective', 'it_dependent', 'daily', false, 'process', 'control_activities', array['R6']::text[], 160),
  ('control', 'C9', 'AR sub-ledger to GL reconciliation', 'The AR sub-ledger is reconciled to the general ledger control account monthly. Reconciling items are aged and cleared within 60 days. Prepared by the AR Accountant and reviewed and signed by the Financial Controller within 5 working days of month end.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R2', 'R6']::text[], 170),
  ('control', 'C10', 'Customer statement circulation and dispute follow-up', 'Statements of account are sent to all active customers monthly; disputes and unreconciled differences reported by customers are logged, investigated and resolved by the Credit team. Positive confirmations are obtained from the top 20 customers at year end.', null, 'detective', 'manual', 'monthly', false, 'process', 'information_communication', array['R1', 'R6']::text[], 180),
  ('control', 'C11', 'AR ageing review and ECL allowance (IFRS 9)', 'The Credit Manager reviews the AR ageing monthly, documents collection status on all balances over 90 days, and the Financial Reporting team calculates the expected credit loss allowance quarterly using the approved provision matrix (historical loss rates by ageing bucket, adjusted for forward-looking factors) plus specific provisions for disputed or legal cases. The ECL calculation and key assumptions are reviewed and approved by the CFO.', null, 'detective', 'manual', 'quarterly', true, 'process', 'control_activities', array['R7', 'R4']::text[], 190),
  ('control', 'C12', 'Segregation of duties in O2C', 'ERP roles prevent the same user from maintaining customer master data, entering orders, issuing credit notes and applying cash. SoD conflicts are reviewed quarterly and any exception is approved by the CFO with a compensating control.', null, 'preventive', 'it_dependent', 'quarterly', true, 'process', 'control_activities', array['R5', 'R6']::text[], 200),
  ('control', 'C13', 'Sales price master maintenance', 'Changes to price lists, discount structures and promotional pricing are approved by the Commercial Director and uploaded by a restricted Sales Operations role; the ERP retains an audit log of price changes reviewed monthly by Finance for unauthorized changes.', null, 'preventive', 'it_dependent', 'event_driven', false, 'process', 'control_activities', array['R2']::text[], 210)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'O2C'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'O2C'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13');

-- ---------------------------------------------------------------------------
-- R2R: Record-to-Report (Financial Close) (7 risks, 13 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('R2R', 'Record-to-Report (Financial Close)', 'Record-to-Report', 'Period-end close, manual journal entries, account reconciliations, estimates and judgements, consolidation, financial statement preparation and disclosure review. Includes entity-level controls over financial reporting oversight.', 30)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Manual journal entries are posted without authorization or support, including top-side entries used to manipulate results (management override of controls).', null, array['existence_occurrence', 'accuracy', 'completeness']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Balance sheet accounts are not reconciled or reconciling items are not investigated, so errors and misappropriation go undetected.', null, array['existence_occurrence', 'completeness', 'accuracy', 'valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Period-end close tasks are omitted or performed out of sequence, resulting in incomplete or inaccurate financial data.', null, array['completeness', 'accuracy', 'cutoff']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Accounting estimates (provisions, impairment, useful lives, ECL, zakat and tax) are based on unsupported assumptions or are not reviewed by management.', null, array['valuation_allocation', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Intercompany balances and transactions do not eliminate, or consolidation entries are incorrect, misstating group financial statements.', null, array['completeness', 'accuracy', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'Financial statements and disclosures do not comply with IFRS as endorsed in the KSA (SOCPA) or CMA reporting requirements, or contain errors not detected before issuance.', null, array['presentation_disclosure', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'New or unusual transactions and changes in accounting standards are not identified and assessed, leading to inappropriate accounting treatment.', null, array['accuracy', 'presentation_disclosure', 'valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('control', 'C1', 'Manual journal entry approval workflow', 'All manual journal entries are prepared with a description and supporting documentation attached in the ERP and routed by workflow to an approver independent of the preparer: Financial Controller for entries up to SAR 500,000 and CFO above that threshold. The system prevents posting without approval and prevents the preparer from approving their own entry.', null, 'preventive', 'it_dependent', 'multiple_daily', true, 'process', 'control_activities', array['R1']::text[], 80),
  ('control', 'C2', 'Post-close journal entry review for management override', 'After each period close, Internal Audit or the Financial Reporting Manager runs a journal entry analytic on all manual entries (posted by senior finance staff, posted outside business hours, round amounts, entries to revenue or reserves, entries with vague descriptions, entries posted after period end into the closed period) and reviews the selected entries to support, documenting conclusions.', null, 'detective', 'it_dependent', 'monthly', true, 'process', 'monitoring', array['R1']::text[], 90),
  ('control', 'C3', 'Balance sheet account reconciliation and review', 'All balance sheet accounts are assigned an owner and risk rating in the reconciliation tool; high-risk accounts (cash, receivables, payables, inventory, fixed assets, accruals, intercompany) are reconciled monthly and lower-risk accounts quarterly. Each reconciliation agrees the GL balance to independent supporting documentation, explains and ages reconciling items, and is reviewed and signed by a reviewer one level above the preparer within 10 working days of period end. Items over 90 days are escalated to the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R2']::text[], 100),
  ('control', 'C4', 'Financial close checklist and timetable', 'The month-end close is governed by a standard close checklist listing every task (sub-ledger close, accruals, depreciation run, FX revaluation, allocations, reconciliations, flux analysis), owner and due day. Task completion is signed off by the task owner and the checklist is reviewed by the Financial Controller before the ledger is closed for the period.', null, 'preventive', 'manual', 'monthly', true, 'process', 'control_activities', array['R3']::text[], 110),
  ('control', 'C5', 'Monthly flux (variance) analysis', 'The Financial Reporting team prepares an analysis of the income statement and balance sheet comparing the current month to prior month, budget and prior year; variances above 10% and SAR 250,000 are explained with reference to business drivers. The CFO reviews the flux analysis and challenges explanations in the monthly close review meeting; minutes evidence the review.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R2', 'R3', 'R4']::text[], 120),
  ('control', 'C6', 'Accounting estimates and judgements review', 'Each significant estimate (ECL, inventory obsolescence, provisions and contingencies, asset impairment, useful lives, zakat/tax provision, employee end-of-service benefits) is supported by a position paper documenting methodology, data inputs, key assumptions and sensitivity, prepared quarterly and reviewed and approved by the CFO. Actuarial and valuation specialist reports are reviewed for consistency with the entity''s data.', null, 'preventive', 'manual', 'quarterly', true, 'process', 'control_activities', array['R4']::text[], 130),
  ('control', 'C7', 'Intercompany reconciliation and elimination', 'Intercompany balances and transactions are matched between counterparties monthly in the intercompany module; mismatches are resolved before the ledger is closed and any unresolved difference above SAR 50,000 is escalated to the Group Financial Controller. Consolidation eliminations are generated by the consolidation system and the elimination report is reviewed for completeness.', null, 'detective', 'it_dependent', 'monthly', true, 'process', 'control_activities', array['R5']::text[], 140),
  ('control', 'C8', 'Consolidation package review', 'Subsidiary reporting packages are validated by the consolidation system (balanced trial balance, mapping to group chart of accounts, movement schedules agree) and the Group Reporting Manager reviews each package for completeness and unusual items before consolidation. Consolidation adjustments (fair value, NCI, FX translation) are reviewed by the Group Financial Controller.', null, 'detective', 'it_dependent', 'quarterly', true, 'process', 'control_activities', array['R5', 'R6']::text[], 150),
  ('control', 'C9', 'Financial statement disclosure checklist and review', 'Interim and annual financial statements are prepared using a lead schedule tie-out to the trial balance and a current IFRS (as endorsed in KSA by SOCPA) disclosure checklist completed by Financial Reporting and reviewed by the Financial Controller. The CFO reviews the draft financial statements, and the Audit Committee reviews and recommends them to the Board before CMA filing.', null, 'detective', 'manual', 'quarterly', true, 'process', 'control_activities', array['R6']::text[], 160),
  ('control', 'C10', 'Technical accounting review of new transactions and standards', 'Business units notify Financial Reporting of new, unusual or significant transactions (acquisitions, new financing, lease modifications, restructuring) through the transaction review protocol; Financial Reporting prepares an accounting memo with the IFRS analysis, reviewed by the CFO and shared with the external auditor. New and amended IFRS standards are assessed annually for impact and the assessment is presented to the Audit Committee.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'risk_assessment', array['R7']::text[], 170),
  ('control', 'C11', 'Audit Committee oversight of financial reporting', 'The Audit Committee, comprising a majority of independent members per CMA Corporate Governance Regulations, meets at least quarterly to review interim and annual financial statements, significant judgements and estimates, external auditor reports, and ICFR deficiencies reported by management and internal audit. Minutes document the matters discussed and conclusions reached.', null, 'detective', 'manual', 'quarterly', true, 'entity', 'control_environment', array['R1', 'R4', 'R6']::text[], 180),
  ('control', 'C12', 'Chart of accounts and GL master data change control', 'Additions and changes to the chart of accounts, cost centres and reporting mappings are requested through a change form, approved by the Financial Reporting Manager and executed by a restricted Finance Systems role; a quarterly report of master data changes is reviewed for unauthorized changes.', null, 'preventive', 'it_dependent', 'event_driven', false, 'process', 'control_activities', array['R3', 'R6']::text[], 190),
  ('control', 'C13', 'Sub-ledger to GL interface completeness', 'Automated interfaces from sub-ledgers (AP, AR, fixed assets, payroll, inventory) and from operational systems post to the GL with control totals; interface exception and suspense reports are reviewed daily by the GL Accountant and items are cleared before period close.', null, 'detective', 'it_dependent', 'daily', false, 'process', 'information_communication', array['R3', 'R2']::text[], 200)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'R2R'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'R2R'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'C13');

-- ---------------------------------------------------------------------------
-- PAY: Payroll & HR (7 risks, 11 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('PAY', 'Payroll & HR', 'Hire-to-Retire', 'Employee onboarding and termination, employee master data, time and attendance, payroll calculation, GOSI and end-of-service benefits, payroll disbursement through WPS and payroll accounting.', 40)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Ghost employees exist on the payroll, or terminated employees continue to be paid.', null, array['existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Unauthorized changes are made to salary, allowances, bank details or grade in the employee master.', null, array['accuracy', 'existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Payroll is calculated incorrectly (overtime, allowances, deductions, GOSI contributions, unpaid leave) due to erroneous inputs or system configuration.', null, array['accuracy', 'valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Payroll costs are incomplete or recorded in the wrong period (accrued bonuses, leave, end-of-service benefits).', null, array['completeness', 'cutoff']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Salary payments are made to the wrong bank accounts or the payment file is altered after approval.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'End-of-service benefit (EOSB) and leave liabilities are not measured in accordance with IAS 19 and the Saudi Labour Law.', null, array['valuation_allocation', 'completeness']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'Payroll expense is misclassified across cost centres, capital projects or functional lines.', null, array['accuracy', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('control', 'C1', 'New hire and termination authorization', 'New employees are added to the HR system only upon an approved requisition, signed employment contract and completed onboarding checklist (Iqama/national ID, GOSI registration, bank details) verified by HR. Terminations are processed within two working days of the approved exit form, with final settlement calculated and approved by the HR Manager and Finance before the last payroll.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'control_activities', array['R1']::text[], 80),
  ('control', 'C2', 'Employee master data change approval and review', 'Changes to sensitive employee master fields (salary, allowances, grade, bank account, cost centre) require an approved change form and are entered by HR and approved in the HR system by the HR Manager. Payroll runs a monthly master data change report, which is compared to approved change forms by the Payroll Supervisor and reviewed by the Finance Manager.', null, 'preventive', 'it_dependent', 'event_driven', true, 'process', 'control_activities', array['R2', 'R5']::text[], 90),
  ('control', 'C3', 'Time, attendance and overtime approval', 'Attendance is captured from the biometric/time system and interfaced to the payroll system; overtime, unpaid leave and shift allowances require line manager approval in the system before the payroll cut-off. The Payroll Supervisor reviews an exceptions report of overtime above 60 hours per month.', null, 'preventive', 'it_dependent', 'monthly', false, 'process', 'control_activities', array['R3']::text[], 100),
  ('control', 'C4', 'Payroll register review and month-on-month reconciliation', 'Before payment, the Payroll Supervisor prepares a reconciliation of the current payroll register to the prior month, explaining movements by joiners, leavers, salary changes and variable pay, and validates the headcount to the approved HR headcount report. The Finance Manager reviews the reconciliation and a sample of individual variances above 10% before approving the payroll.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R1', 'R2', 'R3']::text[], 110),
  ('control', 'C5', 'Payroll system configuration and statutory tables', 'Payroll calculation rules (GOSI rates and ceilings, overtime formulas, EOSB accrual rules, allowance policies) are configured in the payroll system by a restricted role; changes are tested and approved by the Payroll Manager and Finance before migration. Statutory rates are validated annually against GOSI and Labour Law updates.', null, 'preventive', 'it_dependent', 'annually', false, 'process', 'control_activities', array['R3', 'R6']::text[], 120),
  ('control', 'C6', 'Payroll payment file approval and WPS release', 'The bank payment file (WPS/SARIE format) is generated from the approved payroll register; the file total and record count are agreed to the register by Treasury before upload, and the payment is released in the bank portal under dual authorization by two signatories independent of HR and Payroll. The bank portal restricts editing of uploaded files.', null, 'preventive', 'it_dependent', 'monthly', true, 'process', 'control_activities', array['R5']::text[], 130),
  ('control', 'C7', 'Payroll to GL reconciliation and cost allocation', 'The Payroll Accountant reconciles the payroll register (gross pay, deductions, employer contributions, net pay) to the GL payroll postings and the bank debit monthly, and reviews the allocation of payroll cost to cost centres and capital projects against HR cost-centre assignments. The reconciliation is reviewed by the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R4', 'R7']::text[], 140),
  ('control', 'C8', 'Payroll accruals (bonus, leave, unpaid salary)', 'At period end, Finance accrues bonuses per approved schemes, unused annual leave from the HR leave balance report, and any salary for days worked but not yet paid; the accrual schedule is reviewed and approved by the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R4']::text[], 150),
  ('control', 'C9', 'End-of-service benefit valuation review', 'The EOSB obligation is calculated annually by an independent actuary under IAS 19 (projected unit credit method) using census data extracted from the HR system and validated by HR and Finance for completeness and accuracy; monthly accruals are based on the actuarial roll-forward. The Financial Controller reviews the actuarial assumptions (discount rate, salary growth, attrition) and reconciles the valuation to the ledger.', null, 'detective', 'manual', 'annually', true, 'process', 'control_activities', array['R6']::text[], 160),
  ('control', 'C10', 'Periodic headcount verification', 'HR performs a semi-annual physical verification (or line manager attestation) of all employees on the payroll against the HR system and the payroll register, including verification of identification documents, and investigates any employee not confirmed.', null, 'detective', 'manual', 'annually', false, 'process', 'monitoring', array['R1']::text[], 170),
  ('control', 'C11', 'Segregation of duties between HR, Payroll and Treasury', 'System roles ensure that HR maintains employee master data, Payroll processes the payroll run, and Treasury releases payments, with no single user holding more than one of these capabilities. Access is reviewed quarterly by the HR Director and Finance Manager.', null, 'preventive', 'it_dependent', 'quarterly', true, 'process', 'control_activities', array['R1', 'R2', 'R5']::text[], 180)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'PAY'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'PAY'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11');

-- ---------------------------------------------------------------------------
-- FA: Fixed Assets (8 risks, 11 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('FA', 'Fixed Assets', 'Acquire-to-Retire', 'Capital expenditure authorization, capital work in progress (CWIP), asset capitalization, depreciation, impairment, physical verification, transfers and disposals under IAS 16, IAS 36 and IFRS 16 (right-of-use assets).', 50)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Capital expenditure is incurred without appropriate authorization or beyond approved budgets.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Costs are inappropriately capitalized (repairs, maintenance, training, abnormal costs) or capital costs are expensed, misstating assets and profit.', null, array['accuracy', 'valuation_allocation', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Completed projects remain in CWIP and are not transferred to fixed assets, delaying the start of depreciation.', null, array['valuation_allocation', 'cutoff', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Depreciation is calculated using incorrect useful lives, residual values, start dates or methods.', null, array['valuation_allocation', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Assets recorded in the register do not physically exist, are lost or stolen, or exist but are not recorded.', null, array['existence_occurrence', 'completeness', 'rights_obligations']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'Impairment indicators are not identified, or impairment is not measured in accordance with IAS 36.', null, array['valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'Disposals and transfers are not authorized or not recorded, resulting in incorrect gains/losses and overstated assets.', null, array['existence_occurrence', 'completeness', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('risk', 'R8', 'Leases are not identified or right-of-use assets and lease liabilities are measured incorrectly under IFRS 16.', null, array['completeness', 'valuation_allocation', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 80),
  ('control', 'C1', 'Capital expenditure request (CER) approval', 'All capital expenditure is authorized through a capital expenditure request stating business case, budget reference, estimated cost and expected useful life, approved per the DoA (Department Head up to SAR 250,000; CEO up to SAR 5 million; Board above). The ERP blocks capex purchase orders not linked to an approved CER and project code, and reports commitments against CER budget.', null, 'preventive', 'it_dependent', 'event_driven', true, 'process', 'control_activities', array['R1']::text[], 90),
  ('control', 'C2', 'Capitalization policy review of project costs', 'The Fixed Asset Accountant reviews costs charged to each project monthly against the capitalization policy (directly attributable costs, borrowing costs on qualifying assets, exclusion of training, admin overheads and abnormal costs) and reclassifies non-qualifying costs to expense. Repairs and maintenance expense above SAR 50,000 per invoice is reviewed for items that should have been capitalized. The review is signed by the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R2']::text[], 100),
  ('control', 'C3', 'CWIP ageing and capitalization review', 'Finance reviews the CWIP ageing report monthly with project managers to identify projects that are substantially complete or available for use; completion certificates trigger transfer to the fixed asset register with the correct asset class, useful life and in-service date. Projects in CWIP over 12 months are reported to the CFO with justification.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R3']::text[], 110),
  ('control', 'C4', 'Asset master creation and depreciation parameters', 'New assets are created in the fixed asset register by the Fixed Asset Accountant with asset class, cost, in-service date, useful life and residual value from the approved capitalization form; asset class defaults in the system drive useful life and depreciation method per the accounting policy, and any override requires Financial Controller approval.', null, 'preventive', 'it_dependent', 'event_driven', true, 'process', 'control_activities', array['R4']::text[], 120),
  ('control', 'C5', 'Depreciation run and reasonableness review', 'Depreciation is calculated automatically by the fixed asset module in the monthly run. The Fixed Asset Accountant performs a reasonableness test (expected depreciation by asset class based on opening balance, additions and disposals versus actual) and investigates differences above 5%; the analysis is reviewed by the Financial Controller.', null, 'detective', 'it_dependent', 'monthly', true, 'process', 'control_activities', array['R4']::text[], 130),
  ('control', 'C6', 'Fixed asset register to GL reconciliation', 'The fixed asset sub-ledger (cost, accumulated depreciation, net book value by class, and CWIP) is reconciled to the general ledger monthly; differences are investigated and cleared, and the reconciliation is reviewed and signed by the Financial Controller.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R5', 'R7']::text[], 140),
  ('control', 'C7', 'Physical verification of fixed assets', 'A physical verification of all tagged assets is performed annually (high-value and movable assets semi-annually) by a team independent of asset custodians, using the asset register and tagging system; discrepancies are investigated, approved for adjustment by the CFO, and the register is updated. Results are reported to the Audit Committee.', null, 'detective', 'manual', 'annually', true, 'process', 'monitoring', array['R5']::text[], 150),
  ('control', 'C8', 'Impairment indicator assessment', 'At each reporting date, Finance completes an IAS 36 impairment indicator checklist (idle assets, obsolescence, physical damage, adverse market or regulatory changes, performance below plan) with input from operations; where indicators exist, a recoverable amount assessment (value in use or fair value less costs of disposal) is prepared and reviewed by the CFO, with key assumptions documented.', null, 'detective', 'manual', 'annually', true, 'process', 'risk_assessment', array['R6']::text[], 160),
  ('control', 'C9', 'Asset disposal and transfer authorization', 'Disposals, write-offs and inter-location transfers require an asset disposal/transfer form approved per the DoA (Department Head and Finance Manager; CFO for net book value above SAR 100,000), with sale proceeds supported by an approved sale process or auction. The Fixed Asset Accountant records the disposal in the register in the month of approval and calculates the gain or loss.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'control_activities', array['R7']::text[], 170),
  ('control', 'C10', 'Lease identification and IFRS 16 measurement', 'Procurement and Legal notify Finance of all new, modified or terminated contracts containing the right to use an identified asset via the contract register; Finance assesses each contract against IFRS 16, records the lease in the lease accounting tool with term, payments and incremental borrowing rate, and the Financial Controller reviews the lease schedule and quarterly roll-forward of ROU assets and lease liabilities.', null, 'preventive', 'manual', 'quarterly', true, 'process', 'control_activities', array['R8']::text[], 180),
  ('control', 'C11', 'Restricted access to the fixed asset register', 'Access to create, modify or retire assets and to change depreciation parameters in the fixed asset module is restricted to the Fixed Asset Accountant and Finance Systems roles; access is reviewed quarterly by the Financial Controller.', null, 'preventive', 'it_dependent', 'quarterly', false, 'process', 'control_activities', array['R4', 'R7']::text[], 190)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'FA'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'FA'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'R8', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11');

-- ---------------------------------------------------------------------------
-- TRS: Treasury & Cash (7 risks, 12 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('TRS', 'Treasury & Cash', 'Treasury & Cash Management', 'Bank account governance, bank signatories, cash and bank reconciliations, electronic payments, borrowings and covenants, investments, foreign exchange and hedging, and cash forecasting.', 60)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Bank accounts are opened, closed or signatories changed without Board or Treasury Committee authorization.', null, array['existence_occurrence', 'rights_obligations']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Cash and bank balances in the ledger do not agree to bank records, and unreconciled items conceal errors or misappropriation.', null, array['existence_occurrence', 'completeness', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Unauthorized or fraudulent electronic payments are executed (including business email compromise and payment file manipulation).', null, array['existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Borrowings, interest and fees are recorded incompletely or inaccurately, and covenant breaches are not identified, affecting classification and disclosure.', null, array['completeness', 'accuracy', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Investments and derivatives are entered into outside approved policy limits or are valued incorrectly (IFRS 9 classification, fair value hierarchy, hedge accounting).', null, array['valuation_allocation', 'rights_obligations', 'presentation_disclosure']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'Foreign currency balances are translated at incorrect rates or FX gains/losses are misstated.', null, array['accuracy', 'valuation_allocation']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'Petty cash and cash on hand are misappropriated or unsupported.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('control', 'C1', 'Bank account and signatory governance', 'Opening or closing bank accounts and changes to authorized signatories require a Board resolution (or Treasury Committee approval under delegated authority) and are executed by the Treasury Manager. Treasury maintains a bank account and mandate register that is confirmed with each bank semi-annually and reviewed by the CFO.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'control_activities', array['R1']::text[], 80),
  ('control', 'C2', 'Bank reconciliation preparation and review', 'Every bank account is reconciled to the bank statement monthly (main operating and collection accounts daily) by a Treasury Accountant who does not process payments; reconciling items are listed, aged and cleared within 30 days, with unusual items (unidentified receipts, stale cheques, unpresented transfers over 30 days) investigated. Each reconciliation is reviewed and signed by the Financial Controller within 5 working days of month end.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R2', 'R3']::text[], 90),
  ('control', 'C3', 'Dual authorization and payment limits in bank portals', 'All electronic payments are initiated by Treasury from ERP-generated payment files and released in the bank portal under dual authorization by two approved signatories, with matrix limits (single signatory prohibited; two Category A signatories above SAR 1 million). Bank portal user access and limits are reconciled to the approved signatory matrix quarterly.', null, 'preventive', 'it_dependent', 'multiple_daily', true, 'process', 'control_activities', array['R3']::text[], 100),
  ('control', 'C4', 'Payment file integrity and beneficiary verification', 'Payment files are transmitted to the bank via host-to-host or encrypted upload; the bank portal displays file hash/total which is agreed by the releasing signatory to the ERP payment run summary. Any request to change a beneficiary bank account received by email or phone is verified through a call-back to a known contact before actioning; urgent payment requests bypassing the ERP are prohibited.', null, 'preventive', 'it_dependent', 'multiple_daily', true, 'process', 'control_activities', array['R3']::text[], 110),
  ('control', 'C5', 'Borrowings register and interest accrual review', 'Treasury maintains a register of all facilities, drawdowns, repayments, interest rates and fees, reconciled monthly to lender statements and to the GL; interest accruals and effective interest rate amortization of transaction costs are calculated and reviewed by the Financial Controller. Loan confirmations are obtained from all lenders at year end.', null, 'detective', 'manual', 'monthly', true, 'process', 'control_activities', array['R4']::text[], 120),
  ('control', 'C6', 'Covenant compliance monitoring', 'Treasury calculates financial covenants (leverage, interest cover, tangible net worth) for each facility quarterly from the closed ledger, compares to the thresholds in the facility agreements, and reports headroom and any breach or forecast breach to the CFO and Audit Committee; breaches are assessed for the impact on current/non-current classification of borrowings.', null, 'detective', 'manual', 'quarterly', true, 'process', 'monitoring', array['R4']::text[], 130),
  ('control', 'C7', 'Investment and hedging policy compliance', 'Investments and derivative transactions are executed only with approved counterparties within the limits (instrument type, tenor, concentration, credit rating) of the Board-approved Treasury Policy, on a deal ticket approved by the Treasury Manager and confirmed independently by Finance against counterparty confirmations. Treasury reports policy compliance and exposures to the Treasury Committee quarterly.', null, 'preventive', 'manual', 'event_driven', true, 'process', 'control_activities', array['R5']::text[], 140),
  ('control', 'C8', 'Investment valuation and hedge accounting review', 'Investments and derivatives are valued at each reporting date using independent price sources or counterparty valuations validated by Finance; IFRS 9 classification, fair value hierarchy level and hedge effectiveness documentation are reviewed by the Financial Controller, and valuation movements are reconciled to the ledger.', null, 'detective', 'manual', 'quarterly', true, 'process', 'control_activities', array['R5']::text[], 150),
  ('control', 'C9', 'Month-end FX rate maintenance and revaluation', 'Period-end exchange rates are uploaded to the ERP rate table from the SAMA/central bank published rates by the Treasury Accountant and verified by a second person before the automated revaluation of monetary balances is run; the FX gain/loss report is reviewed by the Financial Controller for reasonableness against exposure and rate movements.', null, 'preventive', 'it_dependent', 'monthly', true, 'process', 'control_activities', array['R6']::text[], 160),
  ('control', 'C10', 'Petty cash imprest and surprise counts', 'Petty cash is operated on an imprest basis with a fixed float, disbursements supported by approved vouchers and receipts, and replenishment approved by the Finance Manager. Finance performs unannounced cash counts at least quarterly and reconciles the count to the imprest balance and ledger.', null, 'detective', 'manual', 'quarterly', false, 'process', 'control_activities', array['R7']::text[], 170),
  ('control', 'C11', 'Cash forecasting and liquidity review', 'Treasury prepares a 13-week rolling cash forecast weekly, compares actual to forecast cash movements, and reports liquidity headroom against facility limits to the CFO; material variances are explained and forecast assumptions updated.', null, 'detective', 'manual', 'weekly', false, 'process', 'information_communication', array['R2', 'R4']::text[], 180),
  ('control', 'C12', 'Segregation of duties in treasury', 'The users who prepare payment files, approve payments, record bank transactions and prepare bank reconciliations are different individuals, enforced through ERP roles and bank portal profiles; the segregation matrix is reviewed by the CFO quarterly.', null, 'preventive', 'it_dependent', 'quarterly', true, 'process', 'control_activities', array['R2', 'R3']::text[], 190)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'TRS'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'TRS'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12');

-- ---------------------------------------------------------------------------
-- ITGC: IT General Controls (7 risks, 12 controls)
-- ---------------------------------------------------------------------------
insert into public.icfr_templates (code, name, cycle, description, sort_order)
values ('ITGC', 'IT General Controls', 'IT General Controls', 'General controls over financially relevant applications, databases, operating systems and infrastructure: logical access, change management, IT operations (batch jobs, backup, incident management) and program development. Supports reliance on automated controls and IT-dependent manual controls in the business cycles.', 70)
on conflict (code) do update set
  name = excluded.name, cycle = excluded.cycle, description = excluded.description, sort_order = excluded.sort_order;

insert into public.icfr_template_items (template_id, kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
select t.id, i.* from public.icfr_templates t
cross join (values
  ('risk', 'R1', 'Users are granted access to financial applications without authorization, or access is not removed on termination or transfer, allowing unauthorized transactions.', null, array['existence_occurrence', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 10),
  ('risk', 'R2', 'Privileged (administrator, superuser, database) access is used to make unauthorized or untraceable changes to financial data or configurations.', null, array['existence_occurrence', 'accuracy', 'completeness']::text[], null, null, null, null::boolean, null, null, null, 20),
  ('risk', 'R3', 'Changes to financial applications, interfaces or reports are made without authorization, testing or approval, causing processing errors.', null, array['accuracy', 'completeness']::text[], null, null, null, null::boolean, null, null, null, 30),
  ('risk', 'R4', 'Developers have access to migrate their own changes to production, circumventing the change control process.', null, array['accuracy', 'existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 40),
  ('risk', 'R5', 'Scheduled batch jobs and interfaces fail or process incompletely without detection, resulting in incomplete or inaccurate financial data.', null, array['completeness', 'accuracy']::text[], null, null, null, null::boolean, null, null, null, 50),
  ('risk', 'R6', 'Financial data is lost or cannot be restored following a system failure or cyber incident.', null, array['completeness', 'existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 60),
  ('risk', 'R7', 'Authentication and password settings are weak, allowing account compromise.', null, array['existence_occurrence']::text[], null, null, null, null::boolean, null, null, null, 70),
  ('control', 'C1', 'User access provisioning approval', 'Access to in-scope financial applications (ERP, treasury, payroll, consolidation) is granted only upon a ticket approved by the user''s line manager and the application business owner, specifying the role in line with the role catalogue; IT Security provisions the role as approved and the ticket is retained as evidence.', null, 'preventive', 'manual', 'event_driven', true, 'itgc', 'control_activities', array['R1']::text[], 80),
  ('control', 'C2', 'Timely de-provisioning on termination and transfer', 'HR notifies IT Security of terminations and transfers through the automated HR-to-identity feed; network (Active Directory) access is disabled on the last working day and application access is removed within 2 working days. A monthly comparison of the HR leaver list to active application accounts is performed by IT Security and reviewed by the IT Manager.', null, 'preventive', 'it_dependent', 'event_driven', true, 'itgc', 'control_activities', array['R1']::text[], 90),
  ('control', 'C3', 'Periodic user access review', 'Application and business owners review a complete listing of users and roles for each in-scope financial application quarterly (privileged access monthly), confirming appropriateness and segregation of duties; revocations identified are actioned within 5 working days and evidence of completion is retained by IT Security.', null, 'detective', 'manual', 'quarterly', true, 'itgc', 'monitoring', array['R1', 'R2']::text[], 100),
  ('control', 'C4', 'Privileged access restriction and monitoring', 'Administrative access to financial applications, databases and operating systems is restricted to named IT personnel through a privileged access management (PAM) tool with check-out approval and session recording; generic and default accounts are disabled or vaulted. Privileged activity logs are reviewed weekly by the IT Security Manager for direct data changes and unauthorized configuration changes.', null, 'preventive', 'it_dependent', 'weekly', true, 'itgc', 'control_activities', array['R2']::text[], 110),
  ('control', 'C5', 'Password and authentication configuration', 'Authentication parameters for in-scope systems are configured per the Information Security Policy (minimum length 12, complexity, 90-day expiry for non-SSO accounts, lockout after 5 attempts, MFA for remote and privileged access); configuration is verified annually by IT Security against the policy and deviations are remediated.', null, 'preventive', 'automated', 'annually', false, 'itgc', 'control_activities', array['R7', 'R1']::text[], 120),
  ('control', 'C6', 'Change request authorization and testing', 'All changes to in-scope applications, interfaces, configurations and financial reports are logged in the change management tool, approved by the business owner before development, tested in a non-production environment with documented test results and user acceptance sign-off, and approved for deployment by the Change Advisory Board (CAB). Emergency changes are approved retrospectively within 2 working days and reviewed by the CAB.', null, 'preventive', 'manual', 'event_driven', true, 'itgc', 'control_activities', array['R3']::text[], 130),
  ('control', 'C7', 'Segregation of development and production migration', 'Developers do not have access to migrate changes into production; deployment is performed by a separate release management team (or automated pipeline with approval gate) with production access restricted accordingly. A quarterly comparison of production transport/deployment logs to approved change tickets is performed by IT Governance to identify unauthorized changes.', null, 'preventive', 'it_dependent', 'quarterly', true, 'itgc', 'control_activities', array['R4', 'R3']::text[], 140),
  ('control', 'C8', 'Batch job and interface monitoring', 'Financially relevant scheduled jobs and interfaces (sub-ledger postings, bank statement imports, payroll interface, consolidation loads) are monitored through the job scheduler; failures generate alerts to IT Operations, are logged as incidents, and are resolved or re-run with business confirmation before the daily close. The IT Operations Manager reviews the daily job failure log and monthly incident trends.', null, 'detective', 'it_dependent', 'daily', true, 'itgc', 'control_activities', array['R5']::text[], 150),
  ('control', 'C9', 'Backup execution and restoration testing', 'Backups of in-scope databases and application servers run daily per the backup schedule with off-site/immutable copies; backup failures are alerted and resolved within 24 hours. Restoration of financial systems is tested at least semi-annually and results are documented and reviewed by the IT Manager.', null, 'detective', 'it_dependent', 'daily', true, 'itgc', 'control_activities', array['R6']::text[], 160),
  ('control', 'C10', 'IT incident and problem management', 'IT incidents affecting financial systems are logged, prioritized and resolved through the service management tool; high-priority incidents and root-cause analyses are reviewed monthly by the IT Manager and reported to the CFO where financial data integrity may have been affected.', null, 'detective', 'manual', 'monthly', false, 'itgc', 'information_communication', array['R5', 'R6']::text[], 170),
  ('control', 'C11', 'Security patching and vulnerability management', 'Critical and high security patches for in-scope systems are applied within the timeframes in the patch management standard (critical within 14 days), following change control; a monthly vulnerability scan report is reviewed by IT Security and overdue remediation is escalated to the CIO.', null, 'preventive', 'it_dependent', 'monthly', false, 'itgc', 'control_activities', array['R7', 'R6']::text[], 180),
  ('control', 'C12', 'Third-party service provider assurance (SOC 1)', 'For outsourced financially relevant services (cloud ERP hosting, payroll bureau, data centre), Finance and IT obtain and review the service provider''s ISAE 3402 / SOC 1 Type II report annually, evaluate exceptions and complementary user entity controls, and document the conclusion on reliance; gaps in coverage are addressed with bridge letters or additional procedures.', null, 'detective', 'manual', 'annually', true, 'itgc', 'monitoring', array['R2', 'R3', 'R6']::text[], 190)
) as i(kind, ref, title, description, assertions, control_type, nature, frequency, is_key, level, coso_component, linked_risk_refs, sort_order)
where t.code = 'ITGC'
on conflict (template_id, ref) do update set
  kind = excluded.kind, title = excluded.title, description = excluded.description,
  assertions = excluded.assertions, control_type = excluded.control_type, nature = excluded.nature,
  frequency = excluded.frequency, is_key = excluded.is_key, level = excluded.level,
  coso_component = excluded.coso_component, linked_risk_refs = excluded.linked_risk_refs,
  sort_order = excluded.sort_order;

delete from public.icfr_template_items i
using public.icfr_templates t
where i.template_id = t.id and t.code = 'ITGC'
  and i.ref not in ('R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12');

commit;
