-- Additive organization-consistent foreign keys for the 60 audited relationships.
-- Existing ID foreign keys retain their CASCADE/SET NULL behavior.
-- No existing row is rewritten or deleted. Validation fails atomically on drift.
set local lock_timeout = '3s';
set local statement_timeout = '60s';

create unique index audit_engagements_tenant_identity_uidx on public.audit_engagements (id, organization_id);
create unique index audit_observations_tenant_identity_uidx on public.audit_observations (id, organization_id);
create unique index audit_plan_items_tenant_identity_uidx on public.audit_plan_items (id, organization_id);
create unique index audit_plans_tenant_identity_uidx on public.audit_plans (id, organization_id);
create unique index audit_procedures_tenant_identity_uidx on public.audit_procedures (id, organization_id);
create unique index audit_universe_tenant_identity_uidx on public.audit_universe (id, organization_id);
create unique index client_workspaces_tenant_identity_uidx on public.client_workspaces (id, organization_id);
create unique index erm_categories_tenant_identity_uidx on public.erm_categories (id, organization_id);
create unique index erm_kris_tenant_identity_uidx on public.erm_kris (id, organization_id);
create unique index erm_risks_tenant_identity_uidx on public.erm_risks (id, organization_id);
create unique index evidence_tenant_identity_uidx on public.evidence (id, organization_id);
create unique index icfr_controls_tenant_identity_uidx on public.icfr_controls (id, organization_id);
create unique index icfr_processes_tenant_identity_uidx on public.icfr_processes (id, organization_id);
create unique index icfr_tests_tenant_identity_uidx on public.icfr_tests (id, organization_id);
create unique index profiles_tenant_identity_uidx on public.profiles (id, organization_id);

alter table public.audit_actions add constraint audit_actions_evidence_id_tenant_fk foreign key (evidence_id, organization_id) references public.evidence (id, organization_id) not valid;
alter table public.audit_actions add constraint audit_actions_observation_id_tenant_fk foreign key (observation_id, organization_id) references public.audit_observations (id, organization_id) not valid;
alter table public.audit_actions add constraint audit_actions_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_actions add constraint audit_actions_verified_by_tenant_fk foreign key (verified_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_engagements add constraint audit_engagements_auditee_owner_id_tenant_fk foreign key (auditee_owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_engagements add constraint audit_engagements_lead_auditor_id_tenant_fk foreign key (lead_auditor_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_engagements add constraint audit_engagements_plan_item_id_tenant_fk foreign key (plan_item_id, organization_id) references public.audit_plan_items (id, organization_id) not valid;
alter table public.audit_engagements add constraint audit_engagements_universe_id_tenant_fk foreign key (universe_id, organization_id) references public.audit_universe (id, organization_id) not valid;
alter table public.audit_observations add constraint audit_observations_engagement_id_tenant_fk foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) not valid;
alter table public.audit_observations add constraint audit_observations_icfr_control_id_tenant_fk foreign key (icfr_control_id, organization_id) references public.icfr_controls (id, organization_id) not valid;
alter table public.audit_plan_items add constraint audit_plan_items_engagement_id_tenant_fk foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) not valid;
alter table public.audit_plan_items add constraint audit_plan_items_plan_id_tenant_fk foreign key (plan_id, organization_id) references public.audit_plans (id, organization_id) not valid;
alter table public.audit_plan_items add constraint audit_plan_items_universe_id_tenant_fk foreign key (universe_id, organization_id) references public.audit_universe (id, organization_id) not valid;
alter table public.audit_plans add constraint audit_plans_approved_by_tenant_fk foreign key (approved_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_procedures add constraint audit_procedures_assigned_to_tenant_fk foreign key (assigned_to, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_procedures add constraint audit_procedures_engagement_id_tenant_fk foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) not valid;
alter table public.audit_universe add constraint audit_universe_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_universe add constraint audit_universe_parent_id_tenant_fk foreign key (parent_id, organization_id) references public.audit_universe (id, organization_id) not valid;
alter table public.audit_workpapers add constraint audit_workpapers_engagement_id_tenant_fk foreign key (engagement_id, organization_id) references public.audit_engagements (id, organization_id) not valid;
alter table public.audit_workpapers add constraint audit_workpapers_evidence_id_tenant_fk foreign key (evidence_id, organization_id) references public.evidence (id, organization_id) not valid;
alter table public.audit_workpapers add constraint audit_workpapers_prepared_by_tenant_fk foreign key (prepared_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.audit_workpapers add constraint audit_workpapers_procedure_id_tenant_fk foreign key (procedure_id, organization_id) references public.audit_procedures (id, organization_id) not valid;
alter table public.audit_workpapers add constraint audit_workpapers_reviewed_by_tenant_fk foreign key (reviewed_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.briefs add constraint briefs_client_workspace_id_tenant_fk foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) not valid;
alter table public.conversations add constraint conversations_created_by_tenant_fk foreign key (created_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_appetite add constraint erm_appetite_approved_by_tenant_fk foreign key (approved_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_appetite add constraint erm_appetite_category_id_tenant_fk foreign key (category_id, organization_id) references public.erm_categories (id, organization_id) not valid;
alter table public.erm_assessments add constraint erm_assessments_assessed_by_tenant_fk foreign key (assessed_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_assessments add constraint erm_assessments_risk_id_tenant_fk foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) not valid;
alter table public.erm_categories add constraint erm_categories_parent_id_tenant_fk foreign key (parent_id, organization_id) references public.erm_categories (id, organization_id) not valid;
alter table public.erm_kri_readings add constraint erm_kri_readings_kri_id_tenant_fk foreign key (kri_id, organization_id) references public.erm_kris (id, organization_id) not valid;
alter table public.erm_kri_readings add constraint erm_kri_readings_recorded_by_tenant_fk foreign key (recorded_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_kris add constraint erm_kris_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_kris add constraint erm_kris_risk_id_tenant_fk foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) not valid;
alter table public.erm_links add constraint erm_links_risk_id_tenant_fk foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) not valid;
alter table public.erm_risk_controls add constraint erm_risk_controls_icfr_control_id_tenant_fk foreign key (icfr_control_id, organization_id) references public.icfr_controls (id, organization_id) not valid;
alter table public.erm_risk_controls add constraint erm_risk_controls_risk_id_tenant_fk foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) not valid;
alter table public.erm_risks add constraint erm_risks_category_id_tenant_fk foreign key (category_id, organization_id) references public.erm_categories (id, organization_id) not valid;
alter table public.erm_risks add constraint erm_risks_client_workspace_id_tenant_fk foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) not valid;
alter table public.erm_risks add constraint erm_risks_created_by_tenant_fk foreign key (created_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_risks add constraint erm_risks_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_risks add constraint erm_risks_sponsor_id_tenant_fk foreign key (sponsor_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_treatments add constraint erm_treatments_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.erm_treatments add constraint erm_treatments_risk_id_tenant_fk foreign key (risk_id, organization_id) references public.erm_risks (id, organization_id) not valid;
alter table public.evidence add constraint evidence_reviewed_by_tenant_fk foreign key (reviewed_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.evidence add constraint evidence_uploaded_by_tenant_fk foreign key (uploaded_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.icfr_controls add constraint icfr_controls_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.icfr_controls add constraint icfr_controls_process_id_tenant_fk foreign key (process_id, organization_id) references public.icfr_processes (id, organization_id) not valid;
alter table public.icfr_deficiencies add constraint icfr_deficiencies_control_id_tenant_fk foreign key (control_id, organization_id) references public.icfr_controls (id, organization_id) not valid;
alter table public.icfr_deficiencies add constraint icfr_deficiencies_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.icfr_deficiencies add constraint icfr_deficiencies_test_id_tenant_fk foreign key (test_id, organization_id) references public.icfr_tests (id, organization_id) not valid;
alter table public.icfr_processes add constraint icfr_processes_client_workspace_id_tenant_fk foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) not valid;
alter table public.icfr_processes add constraint icfr_processes_owner_id_tenant_fk foreign key (owner_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.icfr_risks add constraint icfr_risks_process_id_tenant_fk foreign key (process_id, organization_id) references public.icfr_processes (id, organization_id) not valid;
alter table public.icfr_tests add constraint icfr_tests_control_id_tenant_fk foreign key (control_id, organization_id) references public.icfr_controls (id, organization_id) not valid;
alter table public.icfr_tests add constraint icfr_tests_tester_id_tenant_fk foreign key (tester_id, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.policies add constraint policies_client_workspace_id_tenant_fk foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) not valid;
alter table public.policies add constraint policies_created_by_tenant_fk foreign key (created_by, organization_id) references public.profiles (id, organization_id) not valid;
alter table public.programs add constraint programs_client_workspace_id_tenant_fk foreign key (client_workspace_id, organization_id) references public.client_workspaces (id, organization_id) not valid;
alter table public.programs add constraint programs_created_by_tenant_fk foreign key (created_by, organization_id) references public.profiles (id, organization_id) not valid;

alter table public.audit_actions validate constraint audit_actions_evidence_id_tenant_fk;
alter table public.audit_actions validate constraint audit_actions_observation_id_tenant_fk;
alter table public.audit_actions validate constraint audit_actions_owner_id_tenant_fk;
alter table public.audit_actions validate constraint audit_actions_verified_by_tenant_fk;
alter table public.audit_engagements validate constraint audit_engagements_auditee_owner_id_tenant_fk;
alter table public.audit_engagements validate constraint audit_engagements_lead_auditor_id_tenant_fk;
alter table public.audit_engagements validate constraint audit_engagements_plan_item_id_tenant_fk;
alter table public.audit_engagements validate constraint audit_engagements_universe_id_tenant_fk;
alter table public.audit_observations validate constraint audit_observations_engagement_id_tenant_fk;
alter table public.audit_observations validate constraint audit_observations_icfr_control_id_tenant_fk;
alter table public.audit_plan_items validate constraint audit_plan_items_engagement_id_tenant_fk;
alter table public.audit_plan_items validate constraint audit_plan_items_plan_id_tenant_fk;
alter table public.audit_plan_items validate constraint audit_plan_items_universe_id_tenant_fk;
alter table public.audit_plans validate constraint audit_plans_approved_by_tenant_fk;
alter table public.audit_procedures validate constraint audit_procedures_assigned_to_tenant_fk;
alter table public.audit_procedures validate constraint audit_procedures_engagement_id_tenant_fk;
alter table public.audit_universe validate constraint audit_universe_owner_id_tenant_fk;
alter table public.audit_universe validate constraint audit_universe_parent_id_tenant_fk;
alter table public.audit_workpapers validate constraint audit_workpapers_engagement_id_tenant_fk;
alter table public.audit_workpapers validate constraint audit_workpapers_evidence_id_tenant_fk;
alter table public.audit_workpapers validate constraint audit_workpapers_prepared_by_tenant_fk;
alter table public.audit_workpapers validate constraint audit_workpapers_procedure_id_tenant_fk;
alter table public.audit_workpapers validate constraint audit_workpapers_reviewed_by_tenant_fk;
alter table public.briefs validate constraint briefs_client_workspace_id_tenant_fk;
alter table public.conversations validate constraint conversations_created_by_tenant_fk;
alter table public.erm_appetite validate constraint erm_appetite_approved_by_tenant_fk;
alter table public.erm_appetite validate constraint erm_appetite_category_id_tenant_fk;
alter table public.erm_assessments validate constraint erm_assessments_assessed_by_tenant_fk;
alter table public.erm_assessments validate constraint erm_assessments_risk_id_tenant_fk;
alter table public.erm_categories validate constraint erm_categories_parent_id_tenant_fk;
alter table public.erm_kri_readings validate constraint erm_kri_readings_kri_id_tenant_fk;
alter table public.erm_kri_readings validate constraint erm_kri_readings_recorded_by_tenant_fk;
alter table public.erm_kris validate constraint erm_kris_owner_id_tenant_fk;
alter table public.erm_kris validate constraint erm_kris_risk_id_tenant_fk;
alter table public.erm_links validate constraint erm_links_risk_id_tenant_fk;
alter table public.erm_risk_controls validate constraint erm_risk_controls_icfr_control_id_tenant_fk;
alter table public.erm_risk_controls validate constraint erm_risk_controls_risk_id_tenant_fk;
alter table public.erm_risks validate constraint erm_risks_category_id_tenant_fk;
alter table public.erm_risks validate constraint erm_risks_client_workspace_id_tenant_fk;
alter table public.erm_risks validate constraint erm_risks_created_by_tenant_fk;
alter table public.erm_risks validate constraint erm_risks_owner_id_tenant_fk;
alter table public.erm_risks validate constraint erm_risks_sponsor_id_tenant_fk;
alter table public.erm_treatments validate constraint erm_treatments_owner_id_tenant_fk;
alter table public.erm_treatments validate constraint erm_treatments_risk_id_tenant_fk;
alter table public.evidence validate constraint evidence_reviewed_by_tenant_fk;
alter table public.evidence validate constraint evidence_uploaded_by_tenant_fk;
alter table public.icfr_controls validate constraint icfr_controls_owner_id_tenant_fk;
alter table public.icfr_controls validate constraint icfr_controls_process_id_tenant_fk;
alter table public.icfr_deficiencies validate constraint icfr_deficiencies_control_id_tenant_fk;
alter table public.icfr_deficiencies validate constraint icfr_deficiencies_owner_id_tenant_fk;
alter table public.icfr_deficiencies validate constraint icfr_deficiencies_test_id_tenant_fk;
alter table public.icfr_processes validate constraint icfr_processes_client_workspace_id_tenant_fk;
alter table public.icfr_processes validate constraint icfr_processes_owner_id_tenant_fk;
alter table public.icfr_risks validate constraint icfr_risks_process_id_tenant_fk;
alter table public.icfr_tests validate constraint icfr_tests_control_id_tenant_fk;
alter table public.icfr_tests validate constraint icfr_tests_tester_id_tenant_fk;
alter table public.policies validate constraint policies_client_workspace_id_tenant_fk;
alter table public.policies validate constraint policies_created_by_tenant_fk;
alter table public.programs validate constraint programs_client_workspace_id_tenant_fk;
alter table public.programs validate constraint programs_created_by_tenant_fk;
