-- =============================================================================
-- Seed: regulatory frameworks
--
-- The frameworks a GCC enterprise or the consultancy serving it actually has to
-- answer to, plus the international standards they are routinely mapped against.
--
-- `catalogue_depth` states honestly how much of each framework is encoded:
--   full     control text held verbatim
--   control  individual controls enumerated by code and title
--   domain   domain / subdomain outline only, used as crosswalk anchors
--
-- `authority_url` always points at the issuing body so a citation in a generated
-- policy can be traced back to source.
-- =============================================================================

insert into public.frameworks (
  code, name, name_ar, short_name, regulator, regulator_code, jurisdiction,
  category, version, effective_date, mandatory, applies_to_sectors,
  applies_to_entities, description, authority_url, citation,
  catalogue_depth, control_count
) values

-- ---------------------------------------------------------------------------
-- Saudi Arabia — National Cybersecurity Authority
-- ---------------------------------------------------------------------------
(
  'NCA-ECC',
  'Essential Cybersecurity Controls',
  'الضوابط الأساسية للأمن السيبراني',
  'ECC',
  'National Cybersecurity Authority',
  'NCA',
  'SA',
  'cybersecurity',
  'ECC-2:2024',
  '2024-01-01',
  true,
  '{government,banking,financial_services,energy,healthcare,telecom,transport,water,critical_infrastructure}',
  'Government entities and their contractors, plus private-sector organisations owning or operating Critical National Infrastructure.',
  'The baseline cybersecurity control set for Saudi Arabia, structured as 5 main domains and 29 subdomains. Compliance is assessed by the NCA and reported through the national compliance tool.',
  'https://nca.gov.sa',
  'NCA ECC-2:2024',
  'domain',
  114
),
(
  'NCA-CSCC',
  'Critical Systems Cybersecurity Controls',
  'ضوابط الأمن السيبراني للأنظمة الحساسة',
  'CSCC',
  'National Cybersecurity Authority',
  'NCA',
  'SA',
  'cybersecurity',
  'CSCC-1:2019',
  '2019-01-01',
  true,
  '{government,banking,energy,healthcare,telecom,critical_infrastructure}',
  'Organisations operating systems classified as critical, where failure would cause national-level impact.',
  'An additional control layer applied on top of the ECC to systems whose loss would have national consequences. Applies only to in-scope critical systems, not the whole estate.',
  'https://nca.gov.sa',
  'NCA CSCC-1:2019',
  'domain',
  73
),
(
  'NCA-CCC',
  'Cloud Cybersecurity Controls',
  'ضوابط الأمن السيبراني للحوسبة السحابية',
  'CCC',
  'National Cybersecurity Authority',
  'NCA',
  'SA',
  'cloud',
  'CCC-1:2020',
  '2020-01-01',
  true,
  '{government,banking,financial_services,healthcare,telecom}',
  'Cloud service providers operating in Saudi Arabia and the cloud service tenants consuming them; controls are split between the two roles.',
  'Splits obligations between Cloud Service Provider and Cloud Service Tenant, which is what makes it usable for shared-responsibility arguments during an audit.',
  'https://nca.gov.sa',
  'NCA CCC-1:2020',
  'domain',
  37
),
(
  'NCA-DCC',
  'Data Cybersecurity Controls',
  'ضوابط أمن البيانات',
  'DCC',
  'National Cybersecurity Authority',
  'NCA',
  'SA',
  'cybersecurity',
  'DCC-1:2022',
  '2022-01-01',
  true,
  '{government,banking,healthcare,telecom,critical_infrastructure}',
  'Government entities and CNI operators handling data across its lifecycle.',
  'Extends the ECC across the data lifecycle — creation, transfer, storage, use and destruction — and is the control set most often cited alongside the PDPL.',
  'https://nca.gov.sa',
  'NCA DCC-1:2022',
  'domain',
  47
),
(
  'NCA-OTCC',
  'Operational Technology Cybersecurity Controls',
  'ضوابط الأمن السيبراني للأنظمة التشغيلية',
  'OTCC',
  'National Cybersecurity Authority',
  'NCA',
  'SA',
  'operational_technology',
  'OTCC-1:2022',
  '2022-01-01',
  true,
  '{energy,water,manufacturing,transport,critical_infrastructure}',
  'Operators of industrial control systems and operational technology environments.',
  'Covers ICS/SCADA and OT estates, including the IT/OT boundary and safety instrumented systems. Required where the ECC alone does not address plant-floor risk.',
  'https://nca.gov.sa',
  'NCA OTCC-1:2022',
  'domain',
  47
),
(
  'NCA-TCC',
  'Telework Cybersecurity Controls',
  'ضوابط الأمن السيبراني للعمل عن بعد',
  'TCC',
  'National Cybersecurity Authority',
  'NCA',
  'SA',
  'cybersecurity',
  'TCC-1:2021',
  '2021-01-01',
  true,
  '{government,banking,financial_services,telecom}',
  'Organisations permitting remote access to internal systems.',
  'Control set for remote working, remote access and the devices used to reach internal environments from outside the perimeter.',
  'https://nca.gov.sa',
  'NCA TCC-1:2021',
  'domain',
  22
),

-- ---------------------------------------------------------------------------
-- Saudi Arabia — SAMA (central bank)
-- ---------------------------------------------------------------------------
(
  'SAMA-CSF',
  'SAMA Cyber Security Framework',
  'إطار الأمن السيبراني - البنك المركزي السعودي',
  'SAMA CSF',
  'Saudi Central Bank',
  'SAMA',
  'SA',
  'financial_services',
  '1.0',
  '2017-05-01',
  true,
  '{banking,insurance,financial_services,payments,fintech}',
  'All entities regulated by SAMA: banks, insurers, financing companies, credit bureaus and payment service providers.',
  'Four domains across 33 subdomains, each stating a Principle, an Objective and Control Considerations. Assessed on a 0-5 maturity scale; SAMA expects member organisations to reach maturity level 3.',
  'https://www.sama.gov.sa',
  'SAMA Cyber Security Framework v1.0 (May 2017)',
  'domain',
  33
),
(
  'SAMA-BCM',
  'SAMA Business Continuity Management Framework',
  'إطار إدارة استمرارية الأعمال',
  'SAMA BCM',
  'Saudi Central Bank',
  'SAMA',
  'SA',
  'business_continuity',
  '1.0',
  '2017-01-01',
  true,
  '{banking,insurance,financial_services,payments}',
  'All SAMA-regulated entities.',
  'Business continuity and operational resilience expectations for SAMA member organisations, including impact analysis, recovery objectives and testing.',
  'https://www.sama.gov.sa',
  'SAMA Business Continuity Management Framework',
  'domain',
  null
),
(
  'SAMA-ITGF',
  'SAMA IT Governance Framework',
  'إطار حوكمة تقنية المعلومات',
  'SAMA ITGF',
  'Saudi Central Bank',
  'SAMA',
  'SA',
  'financial_services',
  '1.0',
  '2019-01-01',
  true,
  '{banking,insurance,financial_services,payments}',
  'All SAMA-regulated entities.',
  'IT governance, portfolio and service management expectations that sit alongside the Cyber Security Framework.',
  'https://www.sama.gov.sa',
  'SAMA IT Governance Framework',
  'domain',
  null
),

-- ---------------------------------------------------------------------------
-- Saudi Arabia — data protection and AI
-- ---------------------------------------------------------------------------
(
  'SA-PDPL',
  'Personal Data Protection Law',
  'نظام حماية البيانات الشخصية',
  'Saudi PDPL',
  'Saudi Data and AI Authority',
  'SDAIA',
  'SA',
  'privacy',
  'Royal Decree M/19 as amended (2023)',
  '2023-09-14',
  true,
  '{all}',
  'Any entity processing the personal data of individuals residing in Saudi Arabia, including controllers outside the Kingdom processing data of residents.',
  'Saudi Arabia''s general data protection law, enforced by SDAIA. Introduces lawful bases, data subject rights, breach notification, records of processing, and restrictions on transfers outside the Kingdom.',
  'https://sdaia.gov.sa',
  'Royal Decree M/19 of 1443H, as amended by M/148 (2023), with Implementing Regulations',
  'control',
  null
),
(
  'SDAIA-AI-ETHICS',
  'AI Ethics Principles',
  'مبادئ أخلاقيات الذكاء الاصطناعي',
  'SDAIA AI Ethics',
  'Saudi Data and AI Authority',
  'SDAIA',
  'SA',
  'ai_governance',
  '1.0',
  '2023-01-01',
  false,
  '{all}',
  'Organisations designing, developing, deploying or procuring AI systems in Saudi Arabia.',
  'Seven principles with a risk-tiering approach. Voluntary in form, but referenced by Saudi government procurement and increasingly expected of regulated entities.',
  'https://sdaia.gov.sa',
  'SDAIA AI Ethics Principles v1.0',
  'control',
  7
),
(
  'SDAIA-GENAI',
  'Generative AI Guidelines',
  'المبادئ التوجيهية للذكاء الاصطناعي التوليدي',
  'SDAIA GenAI',
  'Saudi Data and AI Authority',
  'SDAIA',
  'SA',
  'ai_governance',
  '2024',
  '2024-01-01',
  false,
  '{all}',
  'Government entities and the private sector adopting generative AI.',
  'Guidance on adopting generative AI: acceptable use, data handling, human oversight, disclosure of AI-generated content, and deepfake-specific considerations.',
  'https://sdaia.gov.sa',
  'SDAIA Generative AI Guidelines (2024)',
  'control',
  null
),

-- ---------------------------------------------------------------------------
-- Qatar
-- ---------------------------------------------------------------------------
(
  'QA-NIA',
  'National Information Assurance Standard',
  'معيار ضمان المعلومات الوطني',
  'Qatar NIA',
  'National Cyber Security Agency',
  'NCSA',
  'QA',
  'cybersecurity',
  'v2.0',
  '2014-01-01',
  true,
  '{government,banking,energy,telecom,transport,critical_infrastructure}',
  'Qatari government agencies and critical sector organisations.',
  'Qatar''s baseline information assurance standard, organised as security domains with a classification-driven and risk-driven control selection process.',
  'https://www.ncsa.gov.qa',
  'Qatar National Information Assurance Standard v2.0',
  'domain',
  null
),
(
  'QCB-TRC',
  'QCB Technology and Information Security Requirements',
  'متطلبات أمن المعلومات - مصرف قطر المركزي',
  'QCB',
  'Qatar Central Bank',
  'QCB',
  'QA',
  'financial_services',
  'current',
  null,
  true,
  '{banking,insurance,financial_services,payments,fintech}',
  'Banks, insurers, finance and payment companies licensed by the Qatar Central Bank.',
  'QCB circulars and rulebook requirements covering technology risk, information security, outsourcing and cloud adoption for licensed financial institutions.',
  'https://www.qcb.gov.qa',
  'Qatar Central Bank circulars and rulebooks',
  'domain',
  null
),
(
  'QA-PDPPL',
  'Personal Data Privacy Protection Law',
  'قانون حماية خصوصية البيانات الشخصية',
  'Qatar PDPPL',
  'Ministry of Communications and Information Technology',
  'MCIT',
  'QA',
  'privacy',
  'Law No. 13 of 2016',
  '2017-06-01',
  true,
  '{all}',
  'Entities processing personal data in Qatar.',
  'The first comprehensive data protection law in the GCC. Establishes consent requirements, data subject rights, special-category data handling and breach notification duties.',
  'https://www.mcit.gov.qa',
  'Qatar Law No. 13 of 2016 on Personal Data Privacy Protection',
  'control',
  null
),

-- ---------------------------------------------------------------------------
-- United Arab Emirates
-- ---------------------------------------------------------------------------
(
  'AE-IA',
  'UAE Information Assurance Regulation',
  'اللوائح التنظيمية لضمان المعلومات',
  'UAE IA',
  'Telecommunications and Digital Government Regulatory Authority',
  'TDRA',
  'AE',
  'cybersecurity',
  'v1.1',
  '2020-01-01',
  true,
  '{government,energy,telecom,transport,banking,critical_infrastructure}',
  'UAE federal entities and critical national infrastructure sectors.',
  'The UAE''s national information assurance control set, split into management and technical control families with priority tiers driving the order of implementation.',
  'https://tdra.gov.ae',
  'UAE Information Assurance Regulation v1.1',
  'domain',
  188
),
(
  'AE-PDPL',
  'Federal Personal Data Protection Law',
  'قانون حماية البيانات الشخصية',
  'UAE PDPL',
  'UAE Data Office',
  'UAE-DO',
  'AE',
  'privacy',
  'Federal Decree-Law No. 45 of 2021',
  '2022-01-02',
  true,
  '{all}',
  'Entities processing personal data in the UAE, outside the financial free zones which have their own regimes.',
  'The UAE''s federal data protection law. Onshore only: DIFC and ADGM operate separate, independently supervised data protection regimes.',
  'https://u.ae',
  'UAE Federal Decree-Law No. 45 of 2021',
  'control',
  null
),
(
  'AE-DIFC-DPL',
  'DIFC Data Protection Law',
  null,
  'DIFC DPL',
  'DIFC Commissioner of Data Protection',
  'DIFC',
  'AE-DIFC',
  'privacy',
  'DIFC Law No. 5 of 2020',
  '2020-07-01',
  true,
  '{banking,financial_services,insurance,professional_services}',
  'Entities established in the Dubai International Financial Centre.',
  'A GDPR-aligned regime for the DIFC, including Regulation 10 obligations on autonomous and semi-autonomous systems — one of the few data protection laws that speaks to AI directly.',
  'https://www.difc.ae',
  'DIFC Law No. 5 of 2020 and DIFC Data Protection Regulations',
  'control',
  null
),
(
  'AE-ADGM-DPR',
  'ADGM Data Protection Regulations',
  null,
  'ADGM DPR',
  'Abu Dhabi Global Market Office of Data Protection',
  'ADGM',
  'AE-ADGM',
  'privacy',
  '2021',
  '2021-02-14',
  true,
  '{banking,financial_services,insurance,professional_services}',
  'Entities established in the Abu Dhabi Global Market.',
  'GDPR-aligned data protection regulations for the ADGM free zone, supervised by its own Office of Data Protection.',
  'https://www.adgm.com',
  'ADGM Data Protection Regulations 2021',
  'control',
  null
),
(
  'CBUAE-ISS',
  'CBUAE Information Security and Technology Risk Standards',
  null,
  'CBUAE',
  'Central Bank of the UAE',
  'CBUAE',
  'AE',
  'financial_services',
  'current',
  null,
  true,
  '{banking,insurance,financial_services,payments,fintech}',
  'Banks, insurers, exchange houses and payment providers licensed by the CBUAE.',
  'CBUAE standards and regulations covering information security, technology risk, outsourcing and consumer protection for licensed financial institutions.',
  'https://www.centralbank.ae',
  'CBUAE regulations and accompanying standards',
  'domain',
  null
),
(
  'AE-DESC-DCS',
  'Dubai Cyber Security Standard',
  null,
  'DESC DCS',
  'Dubai Electronic Security Center',
  'DESC',
  'AE',
  'cybersecurity',
  'v1.1',
  '2017-01-01',
  true,
  '{government,telecom,transport,energy,critical_infrastructure}',
  'Dubai government entities and Dubai-based critical infrastructure operators.',
  'Emirate-level cybersecurity standard for Dubai, risk-tiered so control obligations scale with the assessed impact level of the entity.',
  'https://www.desc.gov.ae',
  'Dubai Cyber Security Standard v1.1',
  'domain',
  null
),

-- ---------------------------------------------------------------------------
-- Jordan
-- ---------------------------------------------------------------------------
(
  'JO-PDPL',
  'Personal Data Protection Law',
  'قانون حماية البيانات الشخصية',
  'Jordan PDPL',
  'Ministry of Digital Economy and Entrepreneurship',
  'MoDEE',
  'JO',
  'privacy',
  'Law No. 24 of 2023',
  '2023-09-17',
  true,
  '{all}',
  'Entities processing personal data in Jordan.',
  'Jordan''s first comprehensive data protection law, overseen by a Personal Data Protection Council. Establishes consent, data subject rights, cross-border transfer conditions and sanctions.',
  'https://www.modee.gov.jo',
  'Jordan Law No. 24 of 2023 on Personal Data Protection',
  'control',
  null
),
(
  'CBJ-CSF',
  'CBJ Cybersecurity and Information Security Instructions',
  null,
  'CBJ',
  'Central Bank of Jordan',
  'CBJ',
  'JO',
  'financial_services',
  'current',
  null,
  true,
  '{banking,financial_services,payments,fintech}',
  'Banks, payment companies and financial institutions licensed by the Central Bank of Jordan.',
  'CBJ instructions on information security, cyber resilience and technology risk governance for licensed institutions, including incident reporting to the Bank.',
  'https://www.cbj.gov.jo',
  'Central Bank of Jordan information security and cyber resilience instructions',
  'domain',
  null
),
(
  'JO-NCSF',
  'Jordan National Cybersecurity Framework',
  null,
  'Jordan NCSF',
  'National Cyber Security Centre',
  'NCSC-JO',
  'JO',
  'cybersecurity',
  'current',
  null,
  true,
  '{government,banking,energy,telecom,healthcare,critical_infrastructure}',
  'Jordanian public sector bodies and critical infrastructure operators.',
  'Jordan''s national framework under Cybersecurity Law No. 16 of 2019, establishing the NCSC and sector obligations for incident reporting and control implementation.',
  'https://www.ncsc.jo',
  'Jordan Cybersecurity Law No. 16 of 2019 and National Cybersecurity Framework',
  'domain',
  null
),

-- ---------------------------------------------------------------------------
-- Kuwait, Bahrain, Oman
-- ---------------------------------------------------------------------------
(
  'KW-CITRA-CSF',
  'CITRA Cybersecurity Framework',
  null,
  'CITRA CSF',
  'Communication and Information Technology Regulatory Authority',
  'CITRA',
  'KW',
  'cybersecurity',
  'current',
  null,
  true,
  '{government,telecom,banking,energy,critical_infrastructure}',
  'Kuwaiti government entities, telecom licensees and critical infrastructure operators.',
  'Kuwait''s national cybersecurity framework and accompanying regulations, including cloud and data classification requirements.',
  'https://citra.gov.kw',
  'CITRA Cybersecurity Framework',
  'domain',
  null
),
(
  'KW-CITRA-DPPR',
  'Data Privacy Protection Regulation',
  null,
  'CITRA DPPR',
  'Communication and Information Technology Regulatory Authority',
  'CITRA',
  'KW',
  'privacy',
  '2021',
  '2021-01-01',
  true,
  '{all}',
  'Telecom and IT service providers in Kuwait handling personal data.',
  'Kuwait''s data privacy regulation covering consent, transparency, cross-border transfer and security of personal data held by regulated providers.',
  'https://citra.gov.kw',
  'CITRA Data Privacy Protection Regulation (2021)',
  'control',
  null
),
(
  'BH-PDPL',
  'Personal Data Protection Law',
  null,
  'Bahrain PDPL',
  'Personal Data Protection Authority',
  'PDPA-BH',
  'BH',
  'privacy',
  'Law No. 30 of 2018',
  '2019-08-01',
  true,
  '{all}',
  'Entities processing personal data in Bahrain.',
  'Bahrain''s data protection law, notable for criminal sanctions and a requirement to notify or obtain prior approval for certain categories of processing.',
  'https://www.pdp.gov.bh',
  'Bahrain Law No. 30 of 2018 on Personal Data Protection',
  'control',
  null
),
(
  'CBB-OM5',
  'CBB Rulebook — Operational Risk and Cyber Security',
  null,
  'CBB',
  'Central Bank of Bahrain',
  'CBB',
  'BH',
  'financial_services',
  'current',
  null,
  true,
  '{banking,insurance,financial_services,payments}',
  'Institutions licensed by the Central Bank of Bahrain.',
  'CBB Rulebook modules governing operational risk, cyber security, outsourcing and business continuity for licensees, including incident reporting timeframes.',
  'https://www.cbb.gov.bh',
  'CBB Rulebook, Operational Risk Management and Cyber Security modules',
  'domain',
  null
),
(
  'OM-PDPL',
  'Personal Data Protection Law',
  null,
  'Oman PDPL',
  'Ministry of Transport, Communications and Information Technology',
  'MTCIT',
  'OM',
  'privacy',
  'Royal Decree 6/2022',
  '2023-02-13',
  true,
  '{all}',
  'Entities processing personal data in Oman.',
  'Oman''s data protection law and executive regulations, introducing consent, data subject rights, breach notification and permit requirements for sensitive processing.',
  'https://www.mtcit.gov.om',
  'Oman Royal Decree 6/2022 and Executive Regulations',
  'control',
  null
),

-- ---------------------------------------------------------------------------
-- International standards
-- ---------------------------------------------------------------------------
(
  'ISO-27001',
  'ISO/IEC 27001:2022 — Information security management systems',
  null,
  'ISO 27001',
  'International Organization for Standardization',
  'ISO',
  'GLOBAL',
  'cybersecurity',
  '2022',
  '2022-10-25',
  false,
  '{all}',
  'Any organisation seeking certification of an information security management system.',
  'The certifiable ISMS standard. Annex A holds 93 controls across four themes and is the lingua franca every GCC framework is mapped through.',
  'https://www.iso.org/standard/27001',
  'ISO/IEC 27001:2022, Annex A',
  'control',
  93
),
(
  'ISO-27701',
  'ISO/IEC 27701:2019 — Privacy information management',
  null,
  'ISO 27701',
  'International Organization for Standardization',
  'ISO',
  'GLOBAL',
  'privacy',
  '2019',
  '2019-08-01',
  false,
  '{all}',
  'Organisations operating an ISMS that also process personally identifiable information.',
  'A privacy extension to ISO 27001, adding PII controller and PII processor control sets. The usual bridge between an ISMS and a data protection law.',
  'https://www.iso.org/standard/71670.html',
  'ISO/IEC 27701:2019',
  'domain',
  null
),
(
  'ISO-42001',
  'ISO/IEC 42001:2023 — AI management systems',
  null,
  'ISO 42001',
  'International Organization for Standardization',
  'ISO',
  'GLOBAL',
  'ai_governance',
  '2023',
  '2023-12-18',
  false,
  '{all}',
  'Organisations developing, providing or using AI systems.',
  'The first certifiable AI management system standard. Increasingly used as the evidence vehicle for demonstrating EU AI Act and SDAIA AI Ethics readiness.',
  'https://www.iso.org/standard/81230.html',
  'ISO/IEC 42001:2023, Annex A',
  'control',
  null
),
(
  'ISO-22301',
  'ISO 22301:2019 — Business continuity management systems',
  null,
  'ISO 22301',
  'International Organization for Standardization',
  'ISO',
  'GLOBAL',
  'business_continuity',
  '2019',
  '2019-10-01',
  false,
  '{all}',
  'Any organisation operating a business continuity management system.',
  'The certifiable BCMS standard, and the reference point behind the SAMA and CBUAE continuity expectations.',
  'https://www.iso.org/standard/75106.html',
  'ISO 22301:2019',
  'domain',
  null
),
(
  'NIST-CSF',
  'NIST Cybersecurity Framework 2.0',
  null,
  'NIST CSF',
  'National Institute of Standards and Technology',
  'NIST',
  'GLOBAL',
  'cybersecurity',
  '2.0',
  '2024-02-26',
  false,
  '{all}',
  'Any organisation; sector- and size-agnostic by design.',
  'Six functions and 22 categories. Version 2.0 added the GOVERN function, which is what makes it map cleanly onto the governance domains of SAMA CSF and NCA ECC.',
  'https://www.nist.gov/cyberframework',
  'NIST CSWP 29, The NIST Cybersecurity Framework (CSF) 2.0',
  'control',
  22
),
(
  'NIST-AI-RMF',
  'NIST AI Risk Management Framework 1.0',
  null,
  'NIST AI RMF',
  'National Institute of Standards and Technology',
  'NIST',
  'GLOBAL',
  'ai_governance',
  '1.0',
  '2023-01-26',
  false,
  '{all}',
  'Organisations designing, developing, deploying or evaluating AI systems.',
  'Four functions — GOVERN, MAP, MEASURE, MANAGE — for managing AI risk. Voluntary, and the most common structure for an AI risk programme that has to satisfy several regimes at once.',
  'https://www.nist.gov/itl/ai-risk-management-framework',
  'NIST AI 100-1, Artificial Intelligence Risk Management Framework 1.0',
  'control',
  null
),
(
  'PCI-DSS',
  'Payment Card Industry Data Security Standard v4.0.1',
  null,
  'PCI DSS',
  'PCI Security Standards Council',
  'PCI-SSC',
  'GLOBAL',
  'payments',
  '4.0.1',
  '2024-06-11',
  true,
  '{banking,payments,retail,ecommerce,fintech,hospitality}',
  'Any entity that stores, processes or transmits cardholder data, and service providers that can affect its security.',
  'Twelve requirements across six goals. Contractually mandatory through the card brands rather than by statute, and audited annually for larger merchants and service providers.',
  'https://www.pcisecuritystandards.org',
  'PCI DSS v4.0.1',
  'control',
  12
),
(
  'SOC2',
  'SOC 2 — Trust Services Criteria',
  null,
  'SOC 2',
  'American Institute of Certified Public Accountants',
  'AICPA',
  'GLOBAL',
  'assurance',
  'TSC 2017 (rev. 2022)',
  '2017-04-01',
  false,
  '{technology,professional_services,financial_services}',
  'Service organisations reporting to customers on the controls relevant to their services.',
  'An attestation report rather than a certification. Security is mandatory; Availability, Processing Integrity, Confidentiality and Privacy are elected by the organisation.',
  'https://www.aicpa-cima.com',
  'AICPA Trust Services Criteria (2017, revised 2022)',
  'control',
  5
),

-- ---------------------------------------------------------------------------
-- European Union — extraterritorial reach into GCC organisations
-- ---------------------------------------------------------------------------
(
  'EU-GDPR',
  'General Data Protection Regulation',
  null,
  'GDPR',
  'European Data Protection Board and national supervisory authorities',
  'EDPB',
  'EU',
  'privacy',
  'Regulation (EU) 2016/679',
  '2018-05-25',
  true,
  '{all}',
  'Controllers and processors established in the EU, and those outside it offering goods or services to, or monitoring, people in the EU.',
  'Reaches GCC organisations through Article 3(2) whenever they target or monitor people in the EU. The reference regime the GCC data protection laws were drafted against.',
  'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
  'Regulation (EU) 2016/679',
  'control',
  null
),
(
  'EU-AI-ACT',
  'EU Artificial Intelligence Act',
  null,
  'EU AI Act',
  'European Commission and national market surveillance authorities',
  'EC',
  'EU',
  'ai_governance',
  'Regulation (EU) 2024/1689',
  '2024-08-01',
  true,
  '{all}',
  'Providers and deployers of AI systems placed on the EU market or whose output is used in the EU, wherever they are established.',
  'Risk-tiered: prohibited practices, high-risk systems, transparency-only systems, and minimal risk, plus a separate regime for general-purpose AI models. Obligations phase in between February 2025 and August 2027.',
  'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
  'Regulation (EU) 2024/1689',
  'control',
  null
),
(
  'EU-DORA',
  'Digital Operational Resilience Act',
  null,
  'DORA',
  'European Supervisory Authorities',
  'ESAs',
  'EU',
  'financial_services',
  'Regulation (EU) 2022/2554',
  '2025-01-17',
  true,
  '{banking,insurance,financial_services,payments,fintech}',
  'EU financial entities and the critical ICT third-party providers serving them.',
  'Five pillars: ICT risk management, incident reporting, resilience testing, third-party risk, and information sharing. Reaches GCC providers designated as critical ICT third parties to EU financial entities.',
  'https://eur-lex.europa.eu/eli/reg/2022/2554/oj',
  'Regulation (EU) 2022/2554',
  'domain',
  null
),
(
  'EU-NIS2',
  'NIS2 Directive',
  null,
  'NIS2',
  'National competent authorities under EU coordination',
  'EU',
  'EU',
  'cybersecurity',
  'Directive (EU) 2022/2555',
  '2024-10-18',
  true,
  '{energy,transport,banking,healthcare,water,telecom,digital_infrastructure,manufacturing}',
  'Essential and important entities in the sectors listed in Annexes I and II, and entities providing services into the EU.',
  'Raises baseline security obligations across critical sectors, with management-body accountability and a 24-hour early warning for significant incidents.',
  'https://eur-lex.europa.eu/eli/dir/2022/2555/oj',
  'Directive (EU) 2022/2555, Article 21',
  'control',
  null
)

on conflict (code) do update set
  name               = excluded.name,
  name_ar            = excluded.name_ar,
  short_name         = excluded.short_name,
  regulator          = excluded.regulator,
  regulator_code     = excluded.regulator_code,
  jurisdiction       = excluded.jurisdiction,
  category           = excluded.category,
  version            = excluded.version,
  effective_date     = excluded.effective_date,
  mandatory          = excluded.mandatory,
  applies_to_sectors = excluded.applies_to_sectors,
  applies_to_entities= excluded.applies_to_entities,
  description        = excluded.description,
  authority_url      = excluded.authority_url,
  citation           = excluded.citation,
  catalogue_depth    = excluded.catalogue_depth,
  control_count      = excluded.control_count,
  updated_at         = now();

-- ---------------------------------------------------------------------------
-- Maturity models, where the framework defines its own assessment scale
-- ---------------------------------------------------------------------------

update public.frameworks
set maturity_model = jsonb_build_object(
  'scale', 'sama_csf_0_5',
  'target_level', 3,
  'levels', jsonb_build_array(
    jsonb_build_object('level', 0, 'name', 'Non-existent',
      'description', 'No documentation and no awareness of the control.'),
    jsonb_build_object('level', 1, 'name', 'Ad-hoc',
      'description', 'The control is performed inconsistently and is undocumented.'),
    jsonb_build_object('level', 2, 'name', 'Repeatable but informal',
      'description', 'The control is performed consistently but relies on individuals rather than documented process.'),
    jsonb_build_object('level', 3, 'name', 'Structured and formalised',
      'description', 'The control is defined, approved and implemented in a structured way. SAMA''s expected minimum.'),
    jsonb_build_object('level', 4, 'name', 'Managed and measurable',
      'description', 'The control is measured, monitored against targets, and deviations are corrected.'),
    jsonb_build_object('level', 5, 'name', 'Adaptive',
      'description', 'The control is continuously improved against the evolving threat landscape.')
  )
)
where code = 'SAMA-CSF';

update public.frameworks
set maturity_model = jsonb_build_object(
  'scale', 'nca_ecc_implementation',
  'target_level', 4,
  'levels', jsonb_build_array(
    jsonb_build_object('level', 1, 'name', 'Not implemented',
      'description', 'The control is not applied.'),
    jsonb_build_object('level', 2, 'name', 'Partially implemented',
      'description', 'The control is applied to part of the scope or without documentation.'),
    jsonb_build_object('level', 3, 'name', 'Implemented',
      'description', 'The control is documented and applied across the defined scope.'),
    jsonb_build_object('level', 4, 'name', 'Implemented and monitored',
      'description', 'Implementation is verified periodically with evidence retained for NCA assessment.')
  )
)
where code = 'NCA-ECC';
